-- ============================================================================
-- MediVerse Dental CMS — seed data (GENERATED, do not edit by hand)
-- Source: src/build.py, src/template.html, src/i18n_bn.py, assets/
-- Regenerate: python3 mediverse-dental/supabase/seed/generate_seed.py
-- Idempotent only on an empty database (run after `supabase db reset`).
-- ============================================================================

begin;

insert into public.media (path, kind, mime, size_bytes, width, height, alt_en, alt_bn, sha256) values
  ('logos/logo-white.png', 'logo', 'image/png', 38993, 500, 260, 'MediVerse Dental logo (white)', null, '00fec8d12d9740db405a9e620dc15e7a3e71fdaa2c9cbf32a0a177fdf75faa3b'),
  ('logos/logo-blue.png', 'logo', 'image/png', 82415, 500, 276, 'MediVerse Dental logo (blue)', null, 'c376e4fcc91422a7438a66cc75595da5c4e61ef65dff2ec543037995e3d3ce25'),
  ('flyers/sdm-full.jpg', 'flyer', 'image/jpeg', 62257, 700, 700, 'SDM Full Course course flyer', null, '7485a25e286117dd74e1c3d9389d9933bfc25412e11b6509cb7db3cb32e884f9'),
  ('flyers/sdm-crash.jpg', 'flyer', 'image/jpeg', 55550, 700, 700, 'SDM Crash Course course flyer', null, '83a8d0ddba78294d7ddccfc3256e13fa202dba0f1e45466faa992d55743b24a3'),
  ('flyers/dental-anatomy.jpg', 'flyer', 'image/jpeg', 47255, 700, 700, 'Dental Anatomy Full Course course flyer', null, '94518fd91fe5f61278ec6857d8b55230a5e5fc84843a33f5a5b234c016e00bd1'),
  ('flyers/anatomy-1.jpg', 'flyer', 'image/jpeg', 69421, 664, 700, 'Anatomy 1st Term course flyer', null, '500121365098ba4fcebee0e3a32fe499ddbb467b1bd0d0f4461485961380725b'),
  ('flyers/anatomy-2.jpg', 'flyer', 'image/jpeg', 84222, 658, 700, 'Anatomy 2nd Term course flyer', null, 'd6ee29151f9edcde1595424c071be566148ec30c1eea96ca114dcf3f3ee21c5e'),
  ('flyers/dental-morphology.jpg', 'flyer', 'image/jpeg', 49072, 597, 700, 'Dental Morphology course flyer', null, '7fb648c41190a5579ac797353d9951a6023fae093e385d7294ffb7f9c8fba770'),
  ('flyers/physiology.jpg', 'flyer', 'image/jpeg', 49737, 615, 700, 'Essential Physiology course flyer', null, '28bf6cf89d942df125f3afa661c19dbc5e1fda29a3b8607b8e2238ae505d9cc7'),
  ('flyers/biochemistry.jpg', 'flyer', 'image/jpeg', 76722, 664, 700, 'Essential Biochemistry course flyer', null, 'a68111e5186ff443a254d623f267bda2118ad95f59ce4d59976cdaa3825e4a58'),
  ('flyers/dental-pharmacology.jpg', 'flyer', 'image/jpeg', 36021, 700, 700, 'Dental Pharmacology course flyer', null, 'cd8736617525b4734590036812ae905bc32f632159a66e9adef8bd78df2b1d6e'),
  ('flyers/pathology.jpg', 'flyer', 'image/jpeg', 42807, 700, 700, 'Essential Pathology for BDS course flyer', null, 'd332537abd995d35ee28d63e20b75d1d576456e66cdb3759553a37238115abc2'),
  ('flyers/microbiology.jpg', 'flyer', 'image/jpeg', 37747, 700, 700, 'Microbiology course flyer', null, '51da140b3001d3dbaa2e34d2e6ada5bb8baeb34004c681e7239a60f4bbf83772'),
  ('flyers/pharmacology.jpg', 'flyer', 'image/jpeg', 28292, 700, 700, 'Pharmacology course flyer', null, 'eb13070f9431b7d2f191dbf1246decf98a3a4c88db7ec98ad713bb8776e9a00b'),
  ('flyers/cc-batch.jpg', 'flyer', 'image/jpeg', 53402, 700, 700, 'C&C — Oral Patho, Medicine & Perio course flyer', null, '93b19a0d35c8f250e056a64aed75fb1a42ca254d5c82dee433289ea11f1825dc'),
  ('flyers/peri-oral-crash.jpg', 'flyer', 'image/jpeg', 67493, 700, 791, 'Crash Course on Peri & Oral Patho course flyer', null, '51f74e0c55129eee39f7c691a83f32f93984d1b4127fb4ddb0ff3c81867a75b9'),
  ('flyers/medicine.jpg', 'flyer', 'image/jpeg', 28485, 700, 700, 'Essential Medicine for BDS course flyer', null, 'b8ce082368c64c714f34272b50ea28b3e075f04ac00ff96086000f40d938890c'),
  ('flyers/surgery.jpg', 'flyer', 'image/jpeg', 72653, 700, 700, 'A Complete Solution of Surgery course flyer', null, 'a58c332fb956b1b4d7ee896b3ffde4a8cc705590b44619d601a1c105a9fca60d'),
  ('flyers/oms.jpg', 'flyer', 'image/jpeg', 50302, 700, 700, 'Mastering Maxillofacial Surgery course flyer', null, 'd072202ee30c08bb63fc1b416670d680e91ae884fe0d423a0df9bc5bd4fff95a'),
  ('flyers/conservative.jpg', 'flyer', 'image/jpeg', 44871, 700, 700, 'Conservative & Endo Core Course course flyer', null, '3a97ceeefe4558350be468657a6f47c1e37deaf4713dd808fd988a0bcc242c3e'),
  ('flyers/orthodontics.jpg', 'flyer', 'image/jpeg', 67094, 664, 700, 'Orthodontics Made Easy course flyer', null, 'd71a5985731a76121ad8d779628fa30b5c634183f22a5b5cdc1cbe0793227e8a'),
  ('flyers/decode-opg.jpg', 'flyer', 'image/jpeg', 66251, 663, 700, 'Decode the OPG course flyer', null, 'eb2afe45e5a95fa7fd931e32ab24f24741bef5948c9af443028a412d34b14503'),
  ('flyers/prosthodontics.jpg', 'flyer', 'image/jpeg', 54890, 700, 700, 'Prosthodontics Made Easy course flyer', null, '292d04eb5f0c2ca49910ab7be74a5a70146b217d9d714f48bbcb81bcf6c23035'),
  ('mentors/tanim.jpg', 'mentor_photo', 'image/jpeg', 133452, 861, 1148, 'Dr. Tanim Ahmed', null, '330e41f6c09dcbc2e375331748968d139348de8f3d7865f4684313cfbba2b827'),
  ('mentors/sifat.jpg', 'mentor_photo', 'image/jpeg', 83735, 810, 1080, 'Dr. M R Sifat', null, '0529bebdb12a3fc785fd93fe99d018811a7c3c68f171826129fb1f68bb9db292'),
  ('mentors/fahim.jpg', 'mentor_photo', 'image/jpeg', 194832, 900, 1200, 'Firoj Ahamed Fahim', null, '4c50d3d0d4251a3545da267b55487a0217cc82c2e99fcad633267a082de20d8f'),
  ('mentors/munir.jpg', 'mentor_photo', 'image/jpeg', 165211, 900, 1200, 'Sirajum Munir', null, 'a8be4e1fede5fad4ff95d3296a7fb98229abbe1dd7543badc3bbc8e1e3d1ae6b'),
  ('mentors/adlul.jpg', 'mentor_photo', 'image/jpeg', 133327, 900, 1200, 'Khondkar Adlul Haque', null, 'f6c5eb34a935491f1066d1280cfa04af4fe8ee410019134396f83dbea08c3f99'),
  ('mentors/siyam.jpg', 'mentor_photo', 'image/jpeg', 102863, 807, 1076, 'Dr. Mahmudul Hasan Siyam', null, '44d56f1d0d26e952a8228402617cc3948f5a84a530cf4c435ac98ac514a4ff17');

insert into public.site_settings (site_name, logo_dark_media_id, logo_light_media_id, seo_title_en, seo_title_bn, seo_description_en, seo_description_bn, whatsapp_number, whatsapp_message_en, copyright_en, copyright_bn, footer_tagline_en, footer_tagline_bn, primary_cta_url) values
  ('MediVerse Dental', (select id from public.media where path = 'logos/logo-white.png'), (select id from public.media where path = 'logos/logo-blue.png'), 'MediVerse Dental — Future Dentistry Begins Here', 'মেডিভার্স ডেন্টাল — ডেন্টিস্ট্রির ভবিষ্যৎ শুরু এখান থেকেই', 'MediVerse Dental — phase-wise BDS courses, expert mentors and exam-focused notes for dental students across Bangladesh.', 'ফেজ ধরে সাজানো BDS কোর্স, অভিজ্ঞ মেন্টর আর পরীক্ষার নোটস — বাংলাদেশের ডেন্টাল স্টুডেন্টদের জন্য।', '+8801726415926', 'Hello MediVerse Dental, I would like to know more about your BDS courses.', 'MediVerse Dental. All rights reserved.', 'মেডিভার্স ডেন্টাল। সর্বস্বত্ব সংরক্ষিত।', 'Made for BDS students, by expert mentors 🦷', 'BDS স্টুডেন্টদের জন্য, এক্সপার্ট মেন্টরদের হাতে বানানো 🦷', 'https://mediversebd.com');

insert into public.phases (code, name_en, name_bn, summary_en, summary_bn, sort_order) values
  (1, '1st Phase', '১ম ফেজ', 'SDM, Dental Anatomy, Physiology, Biochemistry — the foundation, with diagram-heavy notes and viva prep.', 'SDM, Dental Anatomy, Physiology, Biochemistry — বেসটা এখানেই শক্ত হয়। সাথে ডায়াগ্রামসহ নোটস আর ভাইভা প্রস্তুতি।', 10),
  (2, '2nd Phase', '২য় ফেজ', 'Pharmacology, Pathology, Microbiology — dense subjects distilled into exam-ready summaries.', 'Pharmacology, Pathology, Microbiology — ভারী ভারী সাবজেক্টগুলো ছোট করে, পরীক্ষার উপযোগী করে গুছিয়ে দেওয়া।', 20),
  (3, '3rd Phase', '৩য় ফেজ', 'Oral Pathology & Medicine, Periodontology, Medicine, Surgery — where clinical thinking takes shape.', 'Oral Pathology & Medicine, Periodontology, Medicine, Surgery — এখান থেকেই ক্লিনিক্যালি ভাবতে শেখা শুরু।', 30),
  (4, 'Final Phase', 'ফাইনাল ফেজ', 'OMS, Conservative, Orthodontics, Prosthodontics, Pedodontics — mastery for finals.', 'OMS, Conservative, Orthodontics, Prosthodontics, Pedodontics — ফাইনালের পুরো প্রস্তুতি।', 40);

insert into public.courses (slug, title_en, title_bn, short_desc_en, short_desc_bn, phase_id, flyer_media_id, external_url, cta_label_en, cta_label_bn, search_keywords, status, sort_order) values
  ('sdm-full-course', 'SDM Full Course', null, 'Complete Science of Dental Materials, exam-mapped from the start.', 'পুরো Science of Dental Materials — শুরু থেকেই পরীক্ষার কথা মাথায় রেখে সাজানো।', (select id from public.phases where code = 1), (select id from public.media where path = 'flyers/sdm-full.jpg'), 'https://mediversebd.com/courses/science-of-dental-materials-full-course', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['science', 'of', 'dental', 'materials']::text[], 'active', 10),
  ('sdm-crash-course', 'SDM Crash Course', null, 'A fast, exam-focused refresher covering SDM''s high-yield topics.', 'SDM-এর ইম্পর্ট্যান্ট টপিকগুলোর ঝটপট রিভিশন — পরীক্ষার ঠিক আগে কাজে লাগবে।', (select id from public.phases where code = 1), (select id from public.media where path = 'flyers/sdm-crash.jpg'), 'https://mediversebd.com/courses/sdm-crash-course', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['science', 'of', 'dental', 'materials', 'revision']::text[], 'active', 20),
  ('dental-anatomy-full-course', 'Dental Anatomy Full Course', null, 'Tooth morphology through full arch relations and occlusion.', 'দাঁতের মরফোলজি থেকে শুরু করে ফুল আর্চ রিলেশন আর অক্লুশন পর্যন্ত।', (select id from public.phases where code = 1), (select id from public.media where path = 'flyers/dental-anatomy.jpg'), 'https://mediversebd.com/courses/dental-anatomy-full-course', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['da', 'tooth', 'morphology']::text[], 'active', 30),
  ('anatomy-1st-term', 'Anatomy 1st Term', null, 'Foundational general anatomy, structured for early BDS.', 'BDS-এর শুরুতে জেনারেল অ্যানাটমির বেসটা শক্ত করার কোর্স।', (select id from public.phases where code = 1), (select id from public.media where path = 'flyers/anatomy-1.jpg'), 'https://mediversebd.com/courses/anatomy-first-term-for-bds', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['general', 'anatomy']::text[], 'active', 40),
  ('anatomy-2nd-term', 'Anatomy 2nd Term', null, 'Continues core anatomy with viva-focused revision notes.', 'অ্যানাটমির বাকি অংশ, সাথে ভাইভার জন্য রিভিশন নোটস।', (select id from public.phases where code = 1), (select id from public.media where path = 'flyers/anatomy-2.jpg'), 'https://mediversebd.com/courses/anatomy-second-term-for-bds', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['general', 'anatomy']::text[], 'active', 50),
  ('dental-morphology', 'Dental Morphology', null, 'Tooth form and function, mapped for practical and theory exams.', 'দাঁতের গঠন আর কাজ — প্র্যাকটিক্যাল আর থিওরি, দুই পরীক্ষার জন্যই।', (select id from public.phases where code = 1), (select id from public.media where path = 'flyers/dental-morphology.jpg'), 'https://mediversebd.com/courses/dental-morphology', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['tooth', 'anatomy']::text[], 'active', 60),
  ('essential-physiology', 'Essential Physiology', null, 'Systems-based physiology notes built for BDS first phase.', 'সিস্টেম ধরে ধরে ফিজিওলজি নোটস, BDS ফার্স্ট ফেজের জন্য বানানো।', (select id from public.phases where code = 1), (select id from public.media where path = 'flyers/physiology.jpg'), 'https://mediversebd.com/courses/essential-physiology-for-bds', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', '{}'::text[], 'active', 70),
  ('essential-biochemistry', 'Essential Biochemistry', null, 'Core biochemical concepts, simplified for dental students.', 'বায়োকেমিস্ট্রির মূল কনসেপ্টগুলো, ডেন্টাল স্টুডেন্টদের জন্য সহজ করে।', (select id from public.phases where code = 1), (select id from public.media where path = 'flyers/biochemistry.jpg'), 'https://mediversebd.com/courses/essential-biochemistry-for-bds', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', '{}'::text[], 'active', 80),
  ('dental-pharmacology', 'Dental Pharmacology', null, 'Drug classes and dental prescriptions, exam-focused.', 'ড্রাগের ক্লাস আর ডেন্টাল প্রেসক্রিপশন — পরীক্ষায় যেভাবে আসে, সেভাবেই।', (select id from public.phases where code = 2), (select id from public.media where path = 'flyers/dental-pharmacology.jpg'), 'https://mediversebd.com/courses/dental-pharmacology', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['drugs', 'prescription']::text[], 'active', 90),
  ('essential-pathology-for-bds', 'Essential Pathology for BDS', null, 'Concept-first notes on inflammation, neoplasia and healing.', 'ইনফ্লামেশন, নিওপ্লাসিয়া, হিলিং — আগে কনসেপ্ট পরিষ্কার, তারপর নোটস।', (select id from public.phases where code = 2), (select id from public.media where path = 'flyers/pathology.jpg'), 'https://mediversebd.com/courses/essential-pathology-for-bds', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['general', 'pathology']::text[], 'active', 100),
  ('microbiology', 'Microbiology', null, 'Organism-wise notes built around board-relevant clinical links.', 'অর্গানিজম ধরে ধরে নোটস, সাথে পরীক্ষায় আসা ক্লিনিক্যাল কানেকশন।', (select id from public.phases where code = 2), (select id from public.media where path = 'flyers/microbiology.jpg'), 'https://mediversebd.com/courses/microbiology-full-course', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['micro']::text[], 'active', 110),
  ('pharmacology', 'Pharmacology', null, 'General pharmacology principles ahead of dental applications.', 'জেনারেল ফার্মাকোলজির বেসিক — ডেন্টাল ফার্মাকোলজিতে ঢোকার আগে।', (select id from public.phases where code = 2), (select id from public.media where path = 'flyers/pharmacology.jpg'), 'https://mediversebd.com/courses/pharmacology-full-course', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['drugs']::text[], 'active', 120),
  ('c-and-c-oral-patho-medicine-and-perio', 'C&C — Oral Patho, Medicine & Perio', null, 'Combined Oral Pathology, Oral Medicine and Periodontology.', 'Oral Pathology, Oral Medicine আর Periodontology — এক কোর্সেই।', (select id from public.phases where code = 3), (select id from public.media where path = 'flyers/cc-batch.jpg'), 'https://mediversebd.com/courses/cawson-carranza', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['cawson', 'carranza', 'oral', 'pathology', 'periodontology']::text[], 'active', 130),
  ('crash-course-on-peri-and-oral-patho', 'Crash Course on Peri & Oral Patho', null, 'Question-based rapid revision of Periodontology and Oral Pathology for written and viva.', 'প্রফের প্রশ্ন ধরে Periodontology আর Oral Pathology-র ঝটপট রিভিশন — লিখিত আর ভাইভা দুটোর জন্যই।', (select id from public.phases where code = 3), (select id from public.media where path = 'flyers/peri-oral-crash.jpg'), 'https://mediversebd.com/courses/crash-course-on-peri-oral-patho', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['cawson', 'carranza', 'perio', 'periodontology', 'oral', 'pathology', 'crash', 'revision']::text[], 'active', 140),
  ('essential-medicine-for-bds', 'Essential Medicine for BDS', null, 'Core general medicine concepts relevant to dental practice and exams.', 'ডেন্টাল প্র্যাকটিস আর পরীক্ষায় যতটুকু মেডিসিন লাগে, ঠিক ততটুকু।', (select id from public.phases where code = 3), (select id from public.media where path = 'flyers/medicine.jpg'), 'https://mediversebd.com/courses/essential-medicine-for-bds', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['general', 'medicine']::text[], 'active', 150),
  ('a-complete-solution-of-surgery', 'A Complete Solution of Surgery', null, 'Full prep for Surgery Paper I — written, viva, OSPE, long and short cases.', 'সার্জারি পেপার ওয়ানের পুরো প্রস্তুতি — লিখিত, ভাইভা, OSPE, লং কেস আর শর্ট কেস।', (select id from public.phases where code = 3), (select id from public.media where path = 'flyers/surgery.jpg'), 'https://mediversebd.com/courses/a-complete-solution-of-surgery', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['general', 'surgery', 'ospe', 'long', 'case', 'short', 'case']::text[], 'active', 160),
  ('mastering-maxillofacial-surgery', 'Mastering Maxillofacial Surgery', null, 'OMS concepts through to exam-format short and long cases.', 'OMS-এর কনসেপ্ট থেকে শুরু করে পরীক্ষার মতো করে শর্ট আর লং কেস।', (select id from public.phases where code = 4), (select id from public.media where path = 'flyers/oms.jpg'), 'https://mediversebd.com/courses/maxillofacial-surgery', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['oms', 'oral', 'surgery']::text[], 'active', 170),
  ('conservative-and-endo-core-course', 'Conservative & Endo Core Course', null, 'Cavity classification through endodontic protocols, simplified.', 'ক্যাভিটি ক্লাসিফিকেশন থেকে এন্ডোডন্টিক প্রোটোকল — সহজ ভাষায়।', (select id from public.phases where code = 4), (select id from public.media where path = 'flyers/conservative.jpg'), 'https://mediversebd.com/courses/conservative-endodontics', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['endodontics', 'operative']::text[], 'active', 180),
  ('orthodontics-made-easy', 'Orthodontics Made Easy', null, 'Core orthodontic concepts distilled for finals revision.', 'অর্থোডন্টিক্সের জরুরি কনসেপ্টগুলো, ফাইনালের রিভিশনের জন্য বেছে আনা।', (select id from public.phases where code = 4), (select id from public.media where path = 'flyers/orthodontics.jpg'), 'https://mediversebd.com/courses/orthodontics-made-easy', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['ortho']::text[], 'active', 190),
  ('decode-the-opg', 'Decode the OPG', null, 'Step-by-step OPG, PNS and OM view interpretation with real cases.', 'রিয়েল কেস দেখে দেখে ধাপে ধাপে OPG, PNS আর OM ভিউ পড়া শেখো।', (select id from public.phases where code = 4), (select id from public.media where path = 'flyers/decode-opg.jpg'), 'https://mediversebd.com/courses/decode-the-opg', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['radiology', 'x-ray', 'opg']::text[], 'active', 200),
  ('prosthodontics-made-easy', 'Prosthodontics Made Easy', null, 'Removable and fixed prosthodontics, exam-focused summaries.', 'রিমুভেবল আর ফিক্সড প্রস্থোডন্টিক্স — পরীক্ষার জন্য গোছানো সামারি।', (select id from public.phases where code = 4), (select id from public.media where path = 'flyers/prosthodontics.jpg'), 'https://mediversebd.com/courses/prosthodontics-made-easy', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['prostho', 'denture']::text[], 'active', 210),
  ('pedodontics-made-easy', 'Pedodontics Made Easy', null, 'Child dental care and management, simplified for finals.', 'বাচ্চাদের ডেন্টাল কেয়ার আর ম্যানেজমেন্ট, ফাইনালের জন্য সহজ করে।', (select id from public.phases where code = 4), null, 'https://mediversebd.com', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['paediatric', 'pediatric', 'children']::text[], 'active', 220);

insert into public.mentors (slug, name, designation_en, designation_bn, credentials, session, photo_media_id, avatar_style, status, sort_order) values
  ('tanim-ahmed', 'Dr. Tanim Ahmed', 'Oral Patho · Perio · OMS · Conservative', null, 'MDCH, Session 2018-19. Expertise: Oral Pathology & Medicine, Periodontology, Oral & Maxillofacial Surgery, Conservative & Endodontics.', '2018-19', (select id from public.media where path = 'mentors/tanim.jpg'), 'photo', 'active', 10),
  ('m-r-sifat', 'Dr. M R Sifat', 'Medicine', null, 'MBBS (DMC), BCS (Health), FCPS P-1 (Medicine), MRCP P-2 (UK). DMC, Session 2014-15.', '2014-15', (select id from public.media where path = 'mentors/sifat.jpg'), 'photo', 'active', 20),
  ('firoj-ahamed-fahim', 'Firoj Ahamed Fahim', 'SDM & Dental Anatomy', null, 'Final year BDS, Sir Salimullah Medical College (Dental Unit), Session 2021-22.', '2021-22', (select id from public.media where path = 'mentors/fahim.jpg'), 'photo', 'active', 30),
  ('sirajum-munir', 'Sirajum Munir', 'General Anatomy', null, 'Pioneer Dental College (PDC), Session 2023-24.', '2023-24', (select id from public.media where path = 'mentors/munir.jpg'), 'photo', 'active', 40),
  ('khondkar-adlul-haque', 'Khondkar Adlul Haque', 'Biochemistry', null, 'Pioneer Dental College (PDC), Session 2023-24.', '2023-24', (select id from public.media where path = 'mentors/adlul.jpg'), 'photo', 'active', 50),
  ('nusrat-jahan-efty', 'Nusrat Jahan Efty', 'Dental Pharmacology', null, 'Sir Salimullah Medical College, Session 2021-22.', '2021-22', null, 'hijab_icon', 'active', 60),
  ('mahmudul-hasan-siyam', 'Dr. Mahmudul Hasan Siyam', 'Prosthodontics', null, 'SSMC, DU. Session 2018-19.', '2018-19', (select id from public.media where path = 'mentors/siyam.jpg'), 'photo', 'active', 70),
  ('faiza-tabassum', 'Dr. Faiza Tabassum', 'Orthodontics', null, 'FCPS Part II Trainee (Dhaka Dental College), Session 2017-18. 3rd in BDS Final Prof (DU). Honours in OMS, Orthodontics, Prosthodontics, Conservative, General Surgery and Dental Anatomy.', '2017-18', null, 'hijab_icon', 'active', 80),
  ('taslima-jahan-lubna', 'Dr. Taslima Jahan Lubna', 'Orthodontics', null, 'Marks Dental College, Session 2010-11. Pursuing MFDS RCSEng Part-1 and FCPS Part-1 (Orthodontics).', '2010-11', null, 'hijab_icon', 'active', 90),
  ('jannatul-ferdous', 'Dr. Jannatul Ferdous', 'Conservative & Endo', null, 'IMC, Session 2014-15. MS at BMU (Conservative Dentistry & Endodontics). Honours in Dental Public Health and Medicine.', '2014-15', null, 'hijab_icon', 'active', 100);

insert into public.course_mentors (course_id, mentor_id, role) values
  ((select id from public.courses where slug = 'sdm-full-course'), (select id from public.mentors where slug = 'firoj-ahamed-fahim'), 'lead'),
  ((select id from public.courses where slug = 'sdm-crash-course'), (select id from public.mentors where slug = 'firoj-ahamed-fahim'), 'lead'),
  ((select id from public.courses where slug = 'dental-anatomy-full-course'), (select id from public.mentors where slug = 'firoj-ahamed-fahim'), 'lead'),
  ((select id from public.courses where slug = 'anatomy-1st-term'), (select id from public.mentors where slug = 'sirajum-munir'), 'lead'),
  ((select id from public.courses where slug = 'c-and-c-oral-patho-medicine-and-perio'), (select id from public.mentors where slug = 'tanim-ahmed'), 'lead'),
  ((select id from public.courses where slug = 'crash-course-on-peri-and-oral-patho'), (select id from public.mentors where slug = 'tanim-ahmed'), 'lead'),
  ((select id from public.courses where slug = 'essential-medicine-for-bds'), (select id from public.mentors where slug = 'm-r-sifat'), 'lead');

insert into public.page_sections (key, sort_order, is_visible, content) values
  ('hero', 10, true, '{"en": {"kicker": "BDS Education · Built for Bangladesh", "heading": "Future Dentistry\n[[Begins Here.]]", "tagline": "ডেন্টাল শিক্ষার নতুন দিগন্ত", "lead": "Phase-wise BDS courses, expert mentors and exam-focused notes — everything a dental student in Bangladesh needs, on one modern platform."}, "bn": {"kicker": "BDS-এর পড়াশোনা · বাংলাদেশের জন্য", "heading": "ডেন্টিস্ট্রির ভবিষ্যৎ\n[[শুরু এখান থেকেই।]]", "tagline": "ডেন্টাল শিক্ষার নতুন দিগন্ত", "lead": "ফেজ ধরে সাজানো BDS কোর্স, অভিজ্ঞ মেন্টর আর পরীক্ষায় সত্যিই কাজে লাগে এমন নোটস — একজন ডেন্টাল স্টুডেন্টের যা যা লাগে, সব এক জায়গায়।"}, "buttons": [{"label_en": "Explore Courses", "label_bn": "কোর্সগুলো দেখো", "url": "#courses", "style": "primary", "new_tab": false}, {"label_en": "Meet the Mentors", "label_bn": "মেন্টরদের চেনো", "url": "#mentors", "style": "ghost", "new_tab": false}]}'::jsonb),
  ('about', 20, true, '{"en": {"kicker": "About MediVerse Dental", "heading": "Dental education, [[re-engineered]] for how you actually study.", "intro": "MediVerse Dental is an academic platform built by expert mentors to help BDS students learn better, prepare smarter and access quality resources — wherever they are in Bangladesh.", "mission_heading": "Our goal is simple — make quality dental education accessible, structured and easier to learn.", "mission_body": "From 1st Prof SDM to Final Prof OMS, every course is mapped to the BDS curriculum and standard textbooks, taught by mentors who have sat the same exams you''re preparing for.", "trust_line": "Trusted by **4,700+ BDS students** from dental colleges nationwide", "highlight_value": "25+", "highlight_label": "Courses covering every BDS professional phase"}, "bn": {"kicker": "মেডিভার্স ডেন্টাল আসলে কী?", "heading": "ডেন্টালের পড়া, [[তোমার মতো করে]] সাজানো।", "intro": "মেডিভার্স ডেন্টাল হলো BDS স্টুডেন্টদের জন্য একটা অনলাইন পড়াশোনার প্ল্যাটফর্ম। ঢাকায় থাকো বা দেশের যেকোনো জায়গায় — বুঝে পড়া, গুছিয়ে প্রস্তুতি নেওয়া আর ভালো রিসোর্স হাতের কাছে পাওয়া, সবই এখানে।", "mission_heading": "আমাদের চাওয়াটা খুব সোজা — ভালো মানের ডেন্টাল পড়াশোনা যেন সবার নাগালে থাকে, গোছানো থাকে, আর পড়তে গিয়ে ঝামেলা না লাগে।", "mission_body": "ফার্স্ট প্রফের SDM থেকে ফাইনাল প্রফের OMS — প্রতিটা কোর্স BDS সিলেবাস আর স্ট্যান্ডার্ড টেক্সটবুক মেনে বানানো। পড়ান সেই মেন্টররা, যারা নিজেরাই এই পরীক্ষাগুলো পার করে এসেছেন।", "trust_line": "দেশের নানা ডেন্টাল কলেজের **৪,৭০০+ স্টুডেন্ট** আমাদের সাথে পড়ছে", "highlight_value": "২৫+", "highlight_label": "কোর্স — BDS-এর প্রতিটা প্রফের জন্য"}, "buttons": []}'::jsonb),
  ('courses', 30, true, '{"en": {"kicker": "Courses", "heading": "Find the course for [[your phase]].", "intro": "Filter by professional phase or search a subject — every course is built from board-relevant textbooks and exam patterns.", "search_placeholder": "Search e.g. OPG, Anatomy, Ortho…"}, "bn": {"kicker": "কোর্স", "heading": "[[তোমার ফেজের]] কোর্সটা খুঁজে নাও।", "intro": "ফেজ বেছে নাও, নয়তো সাবজেক্টের নাম লিখে সার্চ করো — প্রতিটা কোর্স টেক্সটবুক আর প্রফের প্রশ্নের ধরন মেনে বানানো।", "search_placeholder": "সার্চ করো, যেমন OPG, Anatomy, Ortho…"}, "buttons": [{"label_en": "See all courses on mediversebd.com", "label_bn": "সব কোর্স দেখো mediversebd.com-এ", "url": "https://mediversebd.com", "style": "ghost", "new_tab": true}]}'::jsonb),
  ('mentors', 40, true, '{"en": {"kicker": "Expert Mentor Panel", "heading": "Learn from expert mentors who''ve [[sat where you''re sitting]].", "intro": "15+ mentors from DMC, DDC, SSMC, MDCH, IMC and more — toppers, FCPS trainees and practising clinicians."}, "bn": {"kicker": "এক্সপার্ট মেন্টর প্যানেল", "heading": "শেখো তাদের কাছে, [[যারা একদিন তোমার জায়গাতেই ছিলেন]]।", "intro": "DMC, DDC, SSMC, MDCH, IMC সহ দেশের নানা কলেজের ১৫+ মেন্টর — কেউ প্রফে টপার, কেউ FCPS ট্রেইনি, কেউ প্র্যাকটিসিং ক্লিনিশিয়ান।"}, "buttons": []}'::jsonb),
  ('stories', 50, true, '{"en": {"kicker": "Student stories", "heading": "What students say after [[MediVerse]]."}, "bn": {"kicker": "স্টুডেন্টদের কথা", "heading": "[[মেডিভার্স]] নিয়ে স্টুডেন্টরা কী বলছে"}, "buttons": []}'::jsonb),
  ('faq', 60, true, '{"en": {"kicker": "FAQ", "heading": "Questions? [[Answered.]]", "intro": "Can''t find what you need? Message us on WhatsApp or Telegram — the MediVerse team usually replies within a few hours."}, "bn": {"kicker": "প্রশ্ন-উত্তর", "heading": "মনে প্রশ্ন? [[উত্তর এখানেই।]]", "intro": "যা খুঁজছ পাচ্ছ না? হোয়াটসঅ্যাপ বা টেলিগ্রামে নক দাও — সাধারণত কয়েক ঘণ্টার মধ্যেই রিপ্লাই পেয়ে যাবে।"}, "buttons": []}'::jsonb),
  ('contact', 70, true, '{"en": {"heading": "Ready to study smarter this term?", "body": "Join thousands of BDS students already learning with MediVerse Dental. Talk to our team or jump straight into a course."}, "bn": {"heading": "এই টার্মে স্মার্টলি পড়তে রেডি?", "body": "হাজারো BDS স্টুডেন্ট এখন মেডিভার্স ডেন্টালে পড়ছে। কিছু জানার থাকলে আমাদের সাথে কথা বলো, নয়তো সরাসরি কোর্সে ঢুকে পড়ো।"}, "buttons": [{"label_en": "Start Learning", "label_bn": "পড়া শুরু করো", "url": "https://mediversebd.com", "style": "primary", "new_tab": true}, {"label_en": "Chat on WhatsApp", "label_bn": "হোয়াটসঅ্যাপে কথা বলো", "url": "https://wa.me/8801726415926?text=Hello%20MediVerse%20Dental%2C%20I%20would%20like%20to%20know%20more%20about%20your%20BDS%20courses.", "style": "ghost", "new_tab": true}]}'::jsonb);

insert into public.stats (value, suffix, label_en, label_bn, sort_order) values
  (4700, '+', 'Students reached', 'স্টুডেন্ট আমাদের সাথে', 10),
  (25, '+', 'Academic courses', 'কোর্স', 20),
  (15, '+', 'Expert mentors', 'এক্সপার্ট মেন্টর', 30),
  (100, '+', 'Free classes', 'ফ্রি ক্লাস', 40);

insert into public.features (icon, title_en, title_bn, body_en, body_bn, sort_order) values
  ('video', 'Recorded + live classes', 'রেকর্ডেড + লাইভ ক্লাস', 'Learn at your pace with HD recordings, then clear doubts in live sessions.', 'রেকর্ডেড ক্লাস দেখো নিজের সময়মতো, আর যেটা বুঝবে না — লাইভে এসে জিজ্ঞেস করে নাও।', 10),
  ('notes', 'Exam-mapped notes', 'পরীক্ষা মাথায় রেখে নোটস', 'Diagram-heavy class notes, viva prep and question practice built for BDS profs.', 'ডায়াগ্রাম দিয়ে বোঝানো নোটস, ভাইভার প্রস্তুতি আর প্রশ্ন সলভ — সবই প্রফের কথা ভেবে।', 20),
  ('chat', '24/7 mentor support', '২৪/৭ মেন্টর সাপোর্ট', 'Chatbox support and a mentor panel that actually replies to your questions.', 'চ্যাটবক্সে যখন খুশি প্রশ্ন করো — মেন্টররা সত্যিই উত্তর দেন।', 30);

insert into public.faqs (question_en, question_bn, answer_en, answer_bn, sort_order) values
  ('How do I enroll in a course?', 'কোর্সে এনরোল করব কীভাবে?', 'Open the course page on [mediversebd.com](https://mediversebd.com), tap Enroll and complete payment (bKash / Nagad / card). You get access in your dashboard right away.', '[mediversebd.com](https://mediversebd.com)-এ গিয়ে কোর্সটা খোলো, Enroll-এ চাপ দাও, তারপর বিকাশ / নগদ / কার্ডে পেমেন্ট করে ফেলো। পেমেন্ট হলেই কোর্স তোমার ড্যাশবোর্ডে চলে আসবে।', 10),
  ('Are classes live or recorded?', 'ক্লাস কি লাইভ, নাকি রেকর্ডেড?', 'Both. Core lectures are recorded so you can study at your own pace; live sessions and doubt-clearing classes are announced on our Facebook group and Telegram channel.', 'দুটোই। মূল ক্লাসগুলো রেকর্ডেড, তাই নিজের সুবিধামতো দেখতে পারবে। লাইভ ক্লাস আর ডাউট সলভিং সেশনের আপডেট পাবে আমাদের ফেসবুক গ্রুপ আর টেলিগ্রাম চ্যানেলে।', 20),
  ('How long do I keep access?', 'কোর্স কতদিন দেখা যাবে?', 'Most full courses give you access for up to 2 years — long enough to revise before your professional exam. Check each course page for exact duration.', 'বেশিরভাগ ফুল কোর্সে ২ বছর পর্যন্ত অ্যাক্সেস থাকে — প্রফের আগে রিভিশন দেওয়ার জন্য যথেষ্ট সময়। কোন কোর্সের মেয়াদ কত, সেটা কোর্স পেজেই লেখা আছে।', 30),
  ('Can I watch on my phone?', 'মোবাইল থেকে ক্লাস করা যাবে?', 'Yes. The platform is website-based and works on any phone, tablet or laptop browser — no app install needed. Bookmarking lets you jump back to where you left off.', 'অবশ্যই। কোনো অ্যাপ নামাতে হবে না — ফোন, ট্যাব বা ল্যাপটপের ব্রাউজার থেকেই চলবে। বুকমার্ক করে রাখলে যেখানে থেমেছিলে, পরে ঠিক সেখান থেকেই শুরু করতে পারবে।', 40),
  ('Do you offer free classes?', 'ফ্রি ক্লাস আছে?', 'Yes — 100+ free classes are on our YouTube channel. Subscribe to [@mediversedental](https://youtube.com/@mediversedental?si=VuCm4kPuqcdEORaJ) to get notified.', 'আছে! আমাদের ইউটিউব চ্যানেলে ১০০+ ফ্রি ক্লাস আছে। নতুন ক্লাসের আপডেট পেতে [@mediversedental](https://youtube.com/@mediversedental?si=VuCm4kPuqcdEORaJ) সাবস্ক্রাইব করে রাখো।', 50);

insert into public.testimonials (quote_en, quote_bn, attribution_en, attribution_bn, source_en, source_bn, sort_order) values
  ('The SDM notes were exactly what came in my viva. I didn''t need any other book that term.', 'SDM-এর নোটসে যা ছিল, ভাইভায় হুবহু সেগুলোই ধরেছে। ওই টার্মে আর অন্য কোনো বই খুলতেই হয়নি।', '3rd Prof student', 'থার্ড প্রফের স্টুডেন্ট', 'Dhaka Dental College', 'ঢাকা ডেন্টাল কলেজ', 10),
  ('Having a mentor actually reply to my questions changed how I studied for finals.', 'প্রশ্ন করলে মেন্টর সত্যি সত্যিই উত্তর দিতেন — ফাইনালের আগে আমার পড়ার ধরনটাই বদলে গেছে।', '4th Prof student', 'ফোর্থ প্রফের স্টুডেন্ট', 'Chattagram Dental College', 'চট্টগ্রাম ডেন্টাল কলেজ', 20),
  ('The OMS case book format matches the exam so closely it felt like practice runs.', 'OMS কেস বুকের ফরম্যাট পরীক্ষার সাথে এত মিলে যায় যে মনে হচ্ছিল আগেই একবার পরীক্ষা দিয়ে ফেলেছি।', 'Final Prof student', 'ফাইনাল প্রফের স্টুডেন্ট', 'BDS, Bangladesh', 'BDS, বাংলাদেশ', 30);

insert into public.nav_items (location, label_en, label_bn, url, is_external, open_new_tab, style, sort_order) values
  ('header', 'About', 'আমাদের কথা', '#about', false, false, 'link', 10),
  ('header', 'Courses', 'কোর্স', '#courses', false, false, 'link', 20),
  ('header', 'Mentors', 'মেন্টর', '#mentors', false, false, 'link', 30),
  ('header', 'Stories', 'রিভিউ', '#stories', false, false, 'link', 40),
  ('header', 'FAQ', 'প্রশ্ন-উত্তর', '#faq', false, false, 'link', 50),
  ('header', 'Enroll Now', 'এনরোল করো', 'https://mediversebd.com', true, true, 'button', 60),
  ('mobile', 'Home', 'হোম', '#top', false, false, 'link', 10),
  ('mobile', 'About MediVerse', 'মেডিভার্স সম্পর্কে', '#about', false, false, 'link', 20),
  ('mobile', 'Courses', 'কোর্স', '#courses', false, false, 'link', 30),
  ('mobile', 'Mentor Panel', 'মেন্টর প্যানেল', '#mentors', false, false, 'link', 40),
  ('mobile', 'Student Stories', 'স্টুডেন্টদের রিভিউ', '#stories', false, false, 'link', 50),
  ('mobile', 'FAQ & Contact', 'প্রশ্ন-উত্তর ও যোগাযোগ', '#faq', false, false, 'link', 60),
  ('mobile', 'Enroll at mediversebd.com', 'mediversebd.com-এ এনরোল করো', 'https://mediversebd.com', true, true, 'button', 70);

insert into public.footer_sections (type, title_en, title_bn, body_en, body_bn, sort_order) values
  ('text', null, null, 'Future Dentistry Begins Here. A BDS education platform guided by expert mentors — phase-wise courses, mentor guidance and exam-focused notes for students across Bangladesh.', 'ডেন্টিস্ট্রির ভবিষ্যৎ শুরু এখান থেকেই। এক্সপার্ট মেন্টরদের হাতে গড়া BDS পড়াশোনার প্ল্যাটফর্ম — সারা দেশের স্টুডেন্টদের জন্য ফেজ অনুযায়ী কোর্স, মেন্টরের গাইডলাইন আর পরীক্ষার নোটস।', 10),
  ('links', 'Courses', 'কোর্স', null, null, 20),
  ('links', 'Explore', 'ঘুরে দেখো', null, null, 30),
  ('links', 'Platform', 'প্ল্যাটফর্ম', null, null, 40);

insert into public.footer_links (section_id, label_en, label_bn, url, is_external, sort_order) values
  ((select id from public.footer_sections where title_en = 'Courses'), '1st Phase', '১ম ফেজ', '#phase-1', false, 10),
  ((select id from public.footer_sections where title_en = 'Courses'), '2nd Phase', '২য় ফেজ', '#phase-2', false, 20),
  ((select id from public.footer_sections where title_en = 'Courses'), '3rd Phase', '৩য় ফেজ', '#phase-3', false, 30),
  ((select id from public.footer_sections where title_en = 'Courses'), 'Final Phase', 'ফাইনাল ফেজ', '#phase-4', false, 40),
  ((select id from public.footer_sections where title_en = 'Explore'), 'About', 'আমাদের কথা', '#about', false, 10),
  ((select id from public.footer_sections where title_en = 'Explore'), 'Mentor Panel', 'মেন্টর প্যানেল', '#mentors', false, 20),
  ((select id from public.footer_sections where title_en = 'Explore'), 'Student Stories', 'স্টুডেন্টদের রিভিউ', '#stories', false, 30),
  ((select id from public.footer_sections where title_en = 'Explore'), 'FAQ', 'প্রশ্ন-উত্তর', '#faq', false, 40),
  ((select id from public.footer_sections where title_en = 'Platform'), 'mediversebd.com', 'mediversebd.com', 'https://mediversebd.com', true, 10),
  ((select id from public.footer_sections where title_en = 'Platform'), 'Contact', 'যোগাযোগ', '#contact', false, 20),
  ((select id from public.footer_sections where title_en = 'Platform'), 'Privacy Policy', 'প্রাইভেসি পলিসি', 'https://mediversebd.com', true, 30),
  ((select id from public.footer_sections where title_en = 'Platform'), 'Terms of Service', 'শর্তাবলি', 'https://mediversebd.com', true, 40);

insert into public.social_links (platform, url, label_en, label_bn, subtitle_en, subtitle_bn, sort_order) values
  ('facebook', 'https://www.facebook.com/share/18R8eQDysQ/', 'Facebook', 'Facebook', 'Updates & community', 'আপডেট আর কমিউনিটি', 10),
  ('youtube', 'https://youtube.com/@mediversedental?si=VuCm4kPuqcdEORaJ', 'YouTube', 'YouTube', '100+ free classes', '১০০+ ফ্রি ক্লাস', 20),
  ('telegram', 'https://t.me/mvdental', 'Telegram', 'Telegram', 'Notes & notices', 'নোটস আর নোটিশ', 30),
  ('whatsapp', 'https://wa.me/8801726415926?text=Hello%20MediVerse%20Dental%2C%20I%20would%20like%20to%20know%20more%20about%20your%20BDS%20courses.', 'WhatsApp', 'WhatsApp', '+880 1726-415926', '+880 1726-415926', 40);

commit;
