-- ============================================================================
-- MediVerse Dental CMS — ONE-TIME STAGING DATABASE SETUP (generated file)
-- Paste this whole file into Supabase → SQL Editor → New query → Run.
--   * All-or-nothing: if any line fails, NOTHING is saved.
--   * Safe to retry after an error. If it was already applied successfully,
--     running it again fails with "already exists" and changes nothing.
-- Generated by scripts/make_staging_setup.py from supabase/migrations + seed.sql
-- ============================================================================

begin;

-- >>>>>>>>>>>>>>>>>>>> 20261002090000_foundation.sql >>>>>>>>>>>>>>>>>>>>
-- ============================================================================
-- MediVerse Dental CMS — 1/5 Foundation
-- Private helper schema, enum types and shared helper functions.
-- ============================================================================

-- Helpers live in a schema that is NOT exposed through the Supabase Data API,
-- so they cannot be called as RPC endpoints. Roles only get USAGE so that RLS
-- policies can evaluate them.
create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to anon, authenticated, service_role;

-- ---------------------------------------------------------------------------
-- Enum types
-- ---------------------------------------------------------------------------
create type public.admin_role          as enum ('owner', 'editor');
create type public.course_status       as enum ('active', 'upcoming', 'hidden');
create type public.mentor_status       as enum ('active', 'hidden');
create type public.avatar_style        as enum ('photo', 'hijab_icon', 'initials');
create type public.media_kind          as enum ('image', 'flyer', 'thumbnail', 'mentor_photo', 'banner', 'logo');
create type public.nav_location        as enum ('header', 'mobile');
create type public.nav_style           as enum ('link', 'button');
create type public.footer_section_type as enum ('links', 'text', 'contact', 'social');
create type public.banner_placement    as enum ('home_top', 'home_mid', 'course_page');
create type public.social_platform     as enum ('facebook', 'youtube', 'telegram', 'whatsapp', 'instagram',
                                                'linkedin', 'tiktok', 'x', 'website', 'email', 'phone');

-- ---------------------------------------------------------------------------
-- Helper functions
-- ---------------------------------------------------------------------------

-- Keeps updated_at current on every UPDATE.
create or replace function private.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- URL allowlist used by CHECK constraints. Allows:
--   https://… / http://…, mailto:, tel:, in-page anchors (#section) and
--   site-relative paths (/courses/x). Rejects javascript:, data:, vbscript:,
--   protocol-relative //host and anything containing whitespace or quotes.
create or replace function private.is_safe_url(u text)
returns boolean
language sql
immutable
set search_path = ''
as $$
  select u is null or (
        char_length(u) <= 2048
    and u !~* '^\s*(javascript|data|vbscript|file):'
    and (
          u ~* '^https?://[^\s<>"''`]+$'
       or u ~* '^mailto:[^\s<>"''`]+$'
       or u ~  '^tel:\+?[0-9 ()-]{3,20}$'
       or u ~  '^#[A-Za-z0-9_-]*$'
       or u ~  '^/(?!/)[^\s<>"''`]*$'
    )
  );
$$;

-- URL-safe slug: lowercase words separated by single hyphens, max 80 chars.
create or replace function private.is_slug(s text)
returns boolean
language sql
immutable
set search_path = ''
as $$
  select s ~ '^[a-z0-9]+(-[a-z0-9]+)*$' and char_length(s) <= 80;
$$;

grant execute on function private.is_safe_url(text) to anon, authenticated, service_role;
grant execute on function private.is_slug(text)     to anon, authenticated, service_role;

-- >>>>>>>>>>>>>>>>>>>> 20261002090100_admin_auth.sql >>>>>>>>>>>>>>>>>>>>
-- ============================================================================
-- MediVerse Dental CMS — 2/5 Admin authentication & authorization + audit log
--
-- Identity is Supabase Auth (auth.users). Public sign-up is disabled in the
-- Auth settings; only users listed in public.admin_users can use the admin
-- panel. Roles:
--   owner  — everything, incl. managing admin users (requires MFA / aal2)
--   editor — content, courses, mentors, header/footer, media
-- ============================================================================

create table public.admin_users (
  user_id      uuid primary key references auth.users (id) on delete cascade,
  role         public.admin_role not null default 'editor',
  display_name text check (char_length(display_name) <= 80),
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

comment on table public.admin_users is
  'Allowlist of admin panel users. Only owners (with MFA) can change it.';

create trigger admin_users_updated_at
  before update on public.admin_users
  for each row execute function private.set_updated_at();

-- ---------------------------------------------------------------------------
-- Authorization helpers (SECURITY DEFINER so they can read admin_users
-- without being blocked by its own RLS; they only ever answer about the
-- caller, identified by auth.uid()).
-- ---------------------------------------------------------------------------
create or replace function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.admin_users where user_id = (select auth.uid())
  );
$$;

create or replace function private.is_owner()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.admin_users
    where user_id = (select auth.uid()) and role = 'owner'
  );
$$;

-- True when the caller's session passed multi-factor authentication.
create or replace function private.has_mfa()
returns boolean
language sql
stable
set search_path = ''
as $$
  select coalesce((select auth.jwt() ->> 'aal'), 'aal1') = 'aal2';
$$;

revoke all on function private.is_admin(), private.is_owner(), private.has_mfa() from public;
grant execute on function private.is_admin(), private.is_owner(), private.has_mfa()
  to anon, authenticated, service_role;

-- ---------------------------------------------------------------------------
-- Guard: never allow the last owner to be removed or demoted.
-- ---------------------------------------------------------------------------
create or replace function private.protect_last_owner()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if old.role = 'owner'
     and (tg_op = 'DELETE' or new.role <> 'owner')
     and (select count(*) from public.admin_users where role = 'owner') <= 1 then
    raise exception 'Cannot remove or demote the last owner'
      using errcode = 'check_violation';
  end if;
  return coalesce(new, old);
end;
$$;

create trigger admin_users_protect_last_owner
  before update or delete on public.admin_users
  for each row execute function private.protect_last_owner();

-- ---------------------------------------------------------------------------
-- One-time bootstrap: promote an existing auth user (invited from the
-- Supabase dashboard) to owner. Callable only by the database owner
-- (SQL editor / CLI), never through the API.
-- ---------------------------------------------------------------------------
create or replace function private.bootstrap_owner(p_email text)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id uuid;
begin
  select id into v_id from auth.users where lower(email) = lower(p_email);
  if v_id is null then
    raise exception 'No auth user with email %', p_email;
  end if;
  insert into public.admin_users (user_id, role)
  values (v_id, 'owner')
  on conflict (user_id) do update set role = 'owner';
  return v_id;
end;
$$;

revoke all on function private.bootstrap_owner(text) from public, anon, authenticated, service_role;

-- ---------------------------------------------------------------------------
-- RLS for admin_users
-- ---------------------------------------------------------------------------
alter table public.admin_users enable row level security;

revoke all on public.admin_users from anon, authenticated;
grant select, insert, update, delete on public.admin_users to authenticated;

-- An admin can see their own row; owners can see everyone.
create policy admin_users_select on public.admin_users
  for select to authenticated
  using (user_id = (select auth.uid()) or (select private.is_owner()));

-- Only owners who passed MFA can add, change or remove admins.
create policy admin_users_insert on public.admin_users
  for insert to authenticated
  with check ((select private.is_owner()) and (select private.has_mfa()));

create policy admin_users_update on public.admin_users
  for update to authenticated
  using ((select private.is_owner()) and (select private.has_mfa()))
  with check ((select private.is_owner()) and (select private.has_mfa()));

create policy admin_users_delete on public.admin_users
  for delete to authenticated
  using ((select private.is_owner()) and (select private.has_mfa()));

-- ============================================================================
-- Audit log — written only by triggers, readable by admins, immutable.
-- ============================================================================
create table public.audit_log (
  id         bigint generated always as identity primary key,
  at         timestamptz not null default now(),
  actor      uuid,                       -- auth.uid(); null = system/seed
  action     text not null check (action in ('INSERT', 'UPDATE', 'DELETE')),
  entity     text not null,              -- table name
  entity_id  text,
  changes    jsonb                       -- INSERT: new row, DELETE: old row, UPDATE: {field: {old, new}}
);

create index audit_log_at_idx on public.audit_log (at desc);
create index audit_log_entity_idx on public.audit_log (entity, entity_id);

create or replace function private.audit_row()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_old jsonb := case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) end;
  v_new jsonb := case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) end;
  v_row jsonb := coalesce(v_new, v_old);
  v_id  text  := coalesce(v_row ->> 'id', v_row ->> 'user_id', v_row ->> 'key',
                          concat_ws(':', v_row ->> 'course_id', v_row ->> 'mentor_id'));
  v_changes jsonb;
begin
  if tg_op = 'UPDATE' then
    select coalesce(jsonb_object_agg(n.key, jsonb_build_object('old', v_old -> n.key, 'new', n.value)), '{}'::jsonb)
      into v_changes
      from jsonb_each(v_new) n
     where n.key <> 'updated_at' and (v_old -> n.key) is distinct from n.value;
    if v_changes = '{}'::jsonb then
      return new;  -- nothing meaningful changed
    end if;
  else
    v_changes := v_row;
  end if;

  insert into public.audit_log (actor, action, entity, entity_id, changes)
  values ((select auth.uid()), tg_op, tg_table_name, v_id, v_changes);

  return coalesce(new, old);
end;
$$;

revoke all on function private.audit_row() from public, anon, authenticated;

create trigger admin_users_audit
  after insert or update or delete on public.admin_users
  for each row execute function private.audit_row();

alter table public.audit_log enable row level security;

revoke all on public.audit_log from anon, authenticated;
grant select on public.audit_log to authenticated;

-- Admins can read; nobody can insert/update/delete through the API.
create policy audit_log_admin_select on public.audit_log
  for select to authenticated
  using ((select private.is_admin()));

-- >>>>>>>>>>>>>>>>>>>> 20261002090200_content.sql >>>>>>>>>>>>>>>>>>>>
-- ============================================================================
-- MediVerse Dental CMS — 3/5 Content
-- Media, site settings, homepage sections, courses, mentors, header & footer.
--
-- Conventions
--   * Visitor-facing text comes in _en / _bn pairs; empty _bn falls back to _en.
--   * Rich text uses a tiny safe markup rendered server-side (never raw HTML):
--       [[text]]   → gradient highlight     \n → line break
--       [label](https://url) → link (FAQ answers / details only)
--   * No admin identifiers are stored in publicly readable tables; who changed
--     what is recorded in public.audit_log.
--   * Images are referenced through public.media with ON DELETE RESTRICT, so a
--     file that is in use can never be deleted.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Media library
-- ---------------------------------------------------------------------------
create table public.media (
  id          uuid primary key default gen_random_uuid(),
  bucket      text not null default 'public-media' check (bucket = 'public-media'),
  path        text not null unique
              check (path ~ '^(flyers|thumbnails|mentors|banners|logos|images)/[A-Za-z0-9][A-Za-z0-9._-]{0,150}\.(jpe?g|png|webp|avif)$'),
  kind        public.media_kind not null,
  mime        text not null check (mime in ('image/jpeg', 'image/png', 'image/webp', 'image/avif')),
  size_bytes  integer not null check (size_bytes > 0 and size_bytes <= 5242880),
  width       integer check (width > 0 and width <= 10000),
  height      integer check (height > 0 and height <= 10000),
  alt_en      text check (char_length(alt_en) <= 300),
  alt_bn      text check (char_length(alt_bn) <= 300),
  sha256      text unique check (sha256 ~ '^[0-9a-f]{64}$'),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index media_kind_idx on public.media (kind, created_at desc);

-- ---------------------------------------------------------------------------
-- Site settings (single row)
-- ---------------------------------------------------------------------------
create table public.site_settings (
  id                     boolean primary key default true check (id),  -- singleton
  site_name              text not null default 'MediVerse Dental' check (char_length(site_name) <= 100),
  logo_dark_media_id     uuid references public.media (id) on delete restrict,  -- logo for dark theme (white)
  logo_light_media_id    uuid references public.media (id) on delete restrict,  -- logo for light theme (blue)
  og_image_media_id      uuid references public.media (id) on delete restrict,
  seo_title_en           text check (char_length(seo_title_en) <= 120),
  seo_title_bn           text check (char_length(seo_title_bn) <= 120),
  seo_description_en     text check (char_length(seo_description_en) <= 300),
  seo_description_bn     text check (char_length(seo_description_bn) <= 300),
  whatsapp_number        text check (whatsapp_number ~ '^\+[0-9]{8,15}$'),
  whatsapp_message_en    text check (char_length(whatsapp_message_en) <= 300),
  contact_email          text check (contact_email ~* '^[^@\s]+@[^@\s]+\.[a-z]{2,}$'),
  contact_phone          text check (contact_phone ~ '^\+?[0-9 ()-]{6,20}$'),
  address_en             text check (char_length(address_en) <= 300),
  address_bn             text check (char_length(address_bn) <= 300),
  copyright_en           text check (char_length(copyright_en) <= 200),
  copyright_bn           text check (char_length(copyright_bn) <= 200),
  footer_tagline_en      text check (char_length(footer_tagline_en) <= 200),
  footer_tagline_bn      text check (char_length(footer_tagline_bn) <= 200),
  primary_cta_url        text check (private.is_safe_url(primary_cta_url)),   -- main Mediverse platform
  analytics_enabled      boolean not null default true,
  analytics_retention_days integer not null default 395 check (analytics_retention_days between 30 and 1095),
  updated_at             timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Homepage sections: hero, about, courses, mentors, stories, faq, contact
-- content shape (validated by the API layer):
--   { "en": { "kicker": "", "heading": "", "body": "", ... },
--     "bn": { ...same keys... },
--     "buttons": [ { "label_en": "", "label_bn": "", "url": "", "style": "primary|ghost", "new_tab": false } ] }
-- ---------------------------------------------------------------------------
create table public.page_sections (
  id          uuid primary key default gen_random_uuid(),
  page        text not null default 'home' check (page in ('home')),
  key         text not null check (key ~ '^[a-z][a-z0-9_]{1,40}$'),
  is_visible  boolean not null default true,
  sort_order  integer not null default 0,
  content     jsonb not null default '{}'::jsonb check (jsonb_typeof(content) = 'object'),
  media_id    uuid references public.media (id) on delete restrict,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (page, key)
);

create table public.stats (
  id          uuid primary key default gen_random_uuid(),
  value       integer not null check (value >= 0),
  suffix      text not null default '' check (char_length(suffix) <= 5),
  label_en    text not null check (char_length(label_en) between 1 and 60),
  label_bn    text check (char_length(label_bn) <= 60),
  is_visible  boolean not null default true,
  sort_order  integer not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table public.features (
  id          uuid primary key default gen_random_uuid(),
  icon        text not null default 'video' check (icon ~ '^[a-z0-9-]{1,30}$'),
  title_en    text not null check (char_length(title_en) between 1 and 120),
  title_bn    text check (char_length(title_bn) <= 120),
  body_en     text check (char_length(body_en) <= 500),
  body_bn     text check (char_length(body_bn) <= 500),
  is_visible  boolean not null default true,
  sort_order  integer not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table public.faqs (
  id           uuid primary key default gen_random_uuid(),
  question_en  text not null check (char_length(question_en) between 1 and 300),
  question_bn  text check (char_length(question_bn) <= 300),
  answer_en    text not null check (char_length(answer_en) between 1 and 3000),
  answer_bn    text check (char_length(answer_bn) <= 3000),
  is_visible   boolean not null default true,
  sort_order   integer not null default 0,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create table public.testimonials (
  id              uuid primary key default gen_random_uuid(),
  quote_en        text not null check (char_length(quote_en) between 1 and 1000),
  quote_bn        text check (char_length(quote_bn) <= 1000),
  attribution_en  text check (char_length(attribution_en) <= 120),   -- e.g. "3rd Prof student"
  attribution_bn  text check (char_length(attribution_bn) <= 120),
  source_en       text check (char_length(source_en) <= 120),        -- e.g. "Dhaka Dental College"
  source_bn       text check (char_length(source_bn) <= 120),
  is_visible      boolean not null default true,
  sort_order      integer not null default 0,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create table public.banners (
  id          uuid primary key default gen_random_uuid(),
  title       text not null check (char_length(title) between 1 and 120),   -- internal name
  media_id    uuid not null references public.media (id) on delete restrict,
  link_url    text check (private.is_safe_url(link_url)),
  placement   public.banner_placement not null default 'home_top',
  starts_at   timestamptz,
  ends_at     timestamptz,
  is_active   boolean not null default true,
  sort_order  integer not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  check (ends_at is null or starts_at is null or ends_at > starts_at)
);

-- ---------------------------------------------------------------------------
-- Courses & mentors
-- ---------------------------------------------------------------------------
create table public.phases (
  id          uuid primary key default gen_random_uuid(),
  code        smallint not null unique check (code between 1 and 9),
  name_en     text not null check (char_length(name_en) between 1 and 60),
  name_bn     text check (char_length(name_bn) <= 60),
  summary_en  text check (char_length(summary_en) <= 500),
  summary_bn  text check (char_length(summary_bn) <= 500),
  sort_order  integer not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table public.courses (
  id                  uuid primary key default gen_random_uuid(),
  slug                text not null unique check (private.is_slug(slug)),
  title_en            text not null check (char_length(title_en) between 1 and 160),
  title_bn            text check (char_length(title_bn) <= 160),
  short_desc_en       text check (char_length(short_desc_en) <= 400),
  short_desc_bn       text check (char_length(short_desc_bn) <= 400),
  details_en          text check (char_length(details_en) <= 20000),
  details_bn          text check (char_length(details_bn) <= 20000),
  -- { "features": [{ "en": "", "bn": "" }], "total_classes": 60, "access_period_en": "", ... }
  info                jsonb not null default '{}'::jsonb check (jsonb_typeof(info) = 'object'),
  phase_id            uuid not null references public.phases (id) on delete restrict,
  flyer_media_id      uuid references public.media (id) on delete restrict,
  thumbnail_media_id  uuid references public.media (id) on delete restrict,
  external_url        text check (private.is_safe_url(external_url) and external_url ~* '^https://'),
  cta_label_en        text check (char_length(cta_label_en) <= 60),
  cta_label_bn        text check (char_length(cta_label_bn) <= 60),
  search_keywords     text[] not null default '{}',
  seo_title_en        text check (char_length(seo_title_en) <= 120),
  seo_title_bn        text check (char_length(seo_title_bn) <= 120),
  seo_description_en  text check (char_length(seo_description_en) <= 300),
  seo_description_bn  text check (char_length(seo_description_bn) <= 300),
  status              public.course_status not null default 'active',
  sort_order          integer not null default 0,
  archived_at         timestamptz,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);
create index courses_listing_idx on public.courses (status, sort_order) where archived_at is null;
create index courses_phase_idx on public.courses (phase_id);

create table public.mentors (
  id               uuid primary key default gen_random_uuid(),
  slug             text not null unique check (private.is_slug(slug)),
  name             text not null check (char_length(name) between 1 and 120),
  designation_en   text check (char_length(designation_en) <= 120),   -- subject tag, e.g. "Orthodontics"
  designation_bn   text check (char_length(designation_bn) <= 120),
  credentials      text check (char_length(credentials) <= 500),      -- e.g. "MBBS (DMC), BCS (Health)"
  bio_en           text check (char_length(bio_en) <= 3000),
  bio_bn           text check (char_length(bio_bn) <= 3000),
  institution      text check (char_length(institution) <= 160),
  session          text check (char_length(session) <= 40),
  photo_media_id   uuid references public.media (id) on delete restrict,
  avatar_style     public.avatar_style not null default 'initials',
  -- [{ "type": "facebook|linkedin|website|…", "url": "https://…" }]
  links            jsonb not null default '[]'::jsonb check (jsonb_typeof(links) = 'array'),
  status           public.mentor_status not null default 'active',
  sort_order       integer not null default 0,
  archived_at      timestamptz,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  check (avatar_style <> 'photo' or photo_media_id is not null)
);
create index mentors_listing_idx on public.mentors (status, sort_order) where archived_at is null;

create table public.course_mentors (
  course_id   uuid not null references public.courses (id) on delete cascade,
  mentor_id   uuid not null references public.mentors (id) on delete cascade,
  role        text not null default 'mentor' check (role ~ '^[a-z_]{1,30}$'),
  sort_order  integer not null default 0,
  created_at  timestamptz not null default now(),
  primary key (course_id, mentor_id)
);
create index course_mentors_mentor_idx on public.course_mentors (mentor_id);

-- ---------------------------------------------------------------------------
-- Header & footer
-- ---------------------------------------------------------------------------
create table public.nav_items (
  id            uuid primary key default gen_random_uuid(),
  location      public.nav_location not null,
  label_en      text not null check (char_length(label_en) between 1 and 60),
  label_bn      text check (char_length(label_bn) <= 60),
  url           text not null check (private.is_safe_url(url)),
  is_external   boolean not null default false,
  open_new_tab  boolean not null default false,
  style         public.nav_style not null default 'link',
  parent_id     uuid references public.nav_items (id) on delete cascade,
  is_visible    boolean not null default true,
  sort_order    integer not null default 0,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create index nav_items_location_idx on public.nav_items (location, sort_order);

create table public.footer_sections (
  id          uuid primary key default gen_random_uuid(),
  type        public.footer_section_type not null default 'links',
  title_en    text check (char_length(title_en) <= 60),
  title_bn    text check (char_length(title_bn) <= 60),
  body_en     text check (char_length(body_en) <= 1000),
  body_bn     text check (char_length(body_bn) <= 1000),
  is_visible  boolean not null default true,
  sort_order  integer not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table public.footer_links (
  id           uuid primary key default gen_random_uuid(),
  section_id   uuid not null references public.footer_sections (id) on delete cascade,
  label_en     text not null check (char_length(label_en) between 1 and 60),
  label_bn     text check (char_length(label_bn) <= 60),
  url          text not null check (private.is_safe_url(url)),
  is_external  boolean not null default false,
  is_visible   boolean not null default true,
  sort_order   integer not null default 0,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create index footer_links_section_idx on public.footer_links (section_id, sort_order);

create table public.social_links (
  id               uuid primary key default gen_random_uuid(),
  platform         public.social_platform not null,
  url              text not null check (private.is_safe_url(url)),
  label_en         text check (char_length(label_en) <= 60),
  label_bn         text check (char_length(label_bn) <= 60),
  subtitle_en      text check (char_length(subtitle_en) <= 80),   -- e.g. "100+ free classes"
  subtitle_bn      text check (char_length(subtitle_bn) <= 80),
  show_in_header   boolean not null default true,    -- mobile menu
  show_in_footer   boolean not null default true,
  show_in_contact  boolean not null default true,
  is_visible       boolean not null default true,
  sort_order       integer not null default 0,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Media usage (for the media library's "used in…" and "unused" filter)
-- security_invoker → the caller's RLS applies.
-- ---------------------------------------------------------------------------
create view public.media_usage
with (security_invoker = true) as
  select m.id as media_id, u.used_by, u.ref_id
  from public.media m
  join lateral (
              select 'courses.flyer'::text as used_by, c.id::text as ref_id from public.courses c where c.flyer_media_id = m.id
    union all select 'courses.thumbnail', c.id::text from public.courses c where c.thumbnail_media_id = m.id
    union all select 'mentors.photo', t.id::text from public.mentors t where t.photo_media_id = m.id
    union all select 'page_sections.image', s.key from public.page_sections s where s.media_id = m.id
    union all select 'banners.image', b.id::text from public.banners b where b.media_id = m.id
    union all select 'site_settings.logo_dark', 'site' from public.site_settings x where x.logo_dark_media_id = m.id
    union all select 'site_settings.logo_light', 'site' from public.site_settings x where x.logo_light_media_id = m.id
    union all select 'site_settings.og_image', 'site' from public.site_settings x where x.og_image_media_id = m.id
  ) u on true;

-- ============================================================================
-- Triggers: updated_at + audit log on every content table
-- ============================================================================
do $$
declare
  t text;
begin
  foreach t in array array[
    'media', 'site_settings', 'page_sections', 'stats', 'features', 'faqs', 'testimonials',
    'banners', 'phases', 'courses', 'mentors', 'nav_items', 'footer_sections',
    'footer_links', 'social_links'
  ] loop
    execute format(
      'create trigger %I before update on public.%I for each row execute function private.set_updated_at()',
      t || '_updated_at', t);
  end loop;

  foreach t in array array[
    'media', 'site_settings', 'page_sections', 'stats', 'features', 'faqs', 'testimonials',
    'banners', 'phases', 'courses', 'mentors', 'course_mentors', 'nav_items', 'footer_sections',
    'footer_links', 'social_links'
  ] loop
    execute format(
      'create trigger %I after insert or update or delete on public.%I for each row execute function private.audit_row()',
      t || '_audit', t);
  end loop;
end;
$$;

-- ============================================================================
-- Row-Level Security
-- ============================================================================

-- Is this media file referenced by something visitors can see?
-- (Unused / draft uploads are hidden from the public API.)
create or replace function private.media_is_public(p_media_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (select 1 from public.courses c
                  where (c.flyer_media_id = p_media_id or c.thumbnail_media_id = p_media_id)
                    and c.status in ('active', 'upcoming') and c.archived_at is null)
      or exists (select 1 from public.mentors t
                  where t.photo_media_id = p_media_id and t.status = 'active' and t.archived_at is null)
      or exists (select 1 from public.page_sections s where s.media_id = p_media_id and s.is_visible)
      or exists (select 1 from public.banners b
                  where b.media_id = p_media_id and b.is_active
                    and (b.starts_at is null or b.starts_at <= now())
                    and (b.ends_at is null or b.ends_at > now()))
      or exists (select 1 from public.site_settings x
                  where p_media_id in (x.logo_dark_media_id, x.logo_light_media_id, x.og_image_media_id));
$$;
revoke all on function private.media_is_public(uuid) from public;
grant execute on function private.media_is_public(uuid) to anon, authenticated, service_role;

do $$
declare
  t text;
begin
  -- Every content table: RLS on, visitors read-only, admins read/write via policies.
  foreach t in array array[
    'media', 'site_settings', 'page_sections', 'stats', 'features', 'faqs', 'testimonials',
    'banners', 'phases', 'courses', 'mentors', 'course_mentors', 'nav_items', 'footer_sections',
    'footer_links', 'social_links'
  ] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on public.%I from anon, authenticated', t);
    execute format('grant select on public.%I to anon', t);
    execute format('grant select, insert, update, delete on public.%I to authenticated', t);

    execute format(
      'create policy %I on public.%I for select to authenticated using ((select private.is_admin()))',
      t || '_admin_select', t);
    execute format(
      'create policy %I on public.%I for insert to authenticated with check ((select private.is_admin()))',
      t || '_admin_insert', t);
    execute format(
      'create policy %I on public.%I for update to authenticated using ((select private.is_admin())) with check ((select private.is_admin()))',
      t || '_admin_update', t);
  end loop;

  -- Delete: editors may delete list items; permanent deletion of courses,
  -- mentors and site settings is owner-only (editors archive instead).
  foreach t in array array[
    'media', 'page_sections', 'stats', 'features', 'faqs', 'testimonials', 'banners',
    'course_mentors', 'nav_items', 'footer_sections', 'footer_links', 'social_links'
  ] loop
    execute format(
      'create policy %I on public.%I for delete to authenticated using ((select private.is_admin()))',
      t || '_admin_delete', t);
  end loop;

  foreach t in array array['courses', 'mentors', 'phases', 'site_settings'] loop
    execute format(
      'create policy %I on public.%I for delete to authenticated using ((select private.is_owner()))',
      t || '_owner_delete', t);
  end loop;
end;
$$;

-- Public (anon + any signed-in user) read policies: only what the website shows.
create policy site_settings_public_read on public.site_settings
  for select to anon, authenticated using (true);

create policy phases_public_read on public.phases
  for select to anon, authenticated using (true);

create policy courses_public_read on public.courses
  for select to anon, authenticated
  using (status in ('active', 'upcoming') and archived_at is null);

create policy mentors_public_read on public.mentors
  for select to anon, authenticated
  using (status = 'active' and archived_at is null);

create policy course_mentors_public_read on public.course_mentors
  for select to anon, authenticated
  using (
    exists (select 1 from public.courses c
             where c.id = course_id and c.status in ('active', 'upcoming') and c.archived_at is null)
    and exists (select 1 from public.mentors t
                 where t.id = mentor_id and t.status = 'active' and t.archived_at is null)
  );

create policy media_public_read on public.media
  for select to anon, authenticated using ((select private.media_is_public(id)));

create policy page_sections_public_read on public.page_sections
  for select to anon, authenticated using (is_visible);

create policy stats_public_read on public.stats
  for select to anon, authenticated using (is_visible);

create policy features_public_read on public.features
  for select to anon, authenticated using (is_visible);

create policy faqs_public_read on public.faqs
  for select to anon, authenticated using (is_visible);

create policy testimonials_public_read on public.testimonials
  for select to anon, authenticated using (is_visible);

create policy banners_public_read on public.banners
  for select to anon, authenticated
  using (is_active and (starts_at is null or starts_at <= now()) and (ends_at is null or ends_at > now()));

create policy nav_items_public_read on public.nav_items
  for select to anon, authenticated using (is_visible);

create policy footer_sections_public_read on public.footer_sections
  for select to anon, authenticated using (is_visible);

create policy footer_links_public_read on public.footer_links
  for select to anon, authenticated
  using (is_visible and exists (select 1 from public.footer_sections s where s.id = section_id and s.is_visible));

create policy social_links_public_read on public.social_links
  for select to anon, authenticated using (is_visible);

-- The usage view is for the admin media library only.
revoke all on public.media_usage from anon, authenticated;
grant select on public.media_usage to authenticated;

-- >>>>>>>>>>>>>>>>>>>> 20261002090300_analytics.sql >>>>>>>>>>>>>>>>>>>>
-- ============================================================================
-- MediVerse Dental CMS — 4/5 Anonymous visitor analytics
--
-- Privacy rules (enforced by schema design):
--   * Visitors are anonymous website visitors — never "students".
--   * No names, emails, phone numbers, IP addresses or raw user-agent strings
--     are stored. visitor_id / session_id are random browser-generated UUIDs.
--   * Referrer is reduced to a domain; country is a 2-letter code from the
--     hosting platform's geo header (the IP itself is discarded).
--   * Only the server (/api/track, using the service role) writes here.
--     Anonymous visitors cannot read or write any analytics table.
--   * Admins can read. Rollups and retention jobs come in a later phase.
-- ============================================================================

create type public.analytics_event_type as enum ('pageview', 'course_view', 'outbound_click', 'engagement');
create type public.device_type as enum ('mobile', 'tablet', 'desktop', 'other');

create table public.analytics_sessions (
  session_id       uuid primary key,
  visitor_id       uuid not null,
  is_new_visitor   boolean not null default false,
  started_at       timestamptz not null default now(),
  last_seen_at     timestamptz not null default now(),
  engaged_ms       bigint not null default 0 check (engaged_ms >= 0),
  pageviews        integer not null default 0 check (pageviews >= 0),
  entry_path       text check (char_length(entry_path) <= 512),
  exit_path        text check (char_length(exit_path) <= 512),
  referrer_domain  text check (referrer_domain ~ '^[a-z0-9.-]{1,253}$'),
  utm_source       text check (char_length(utm_source) <= 100),
  utm_medium       text check (char_length(utm_medium) <= 100),
  utm_campaign     text check (char_length(utm_campaign) <= 100),
  device_type      public.device_type,
  browser          text check (char_length(browser) <= 40),
  os               text check (char_length(os) <= 40),
  country          text check (country ~ '^[A-Z]{2}$'),
  lang             text check (lang in ('en', 'bn'))
);
create index analytics_sessions_started_idx on public.analytics_sessions (started_at);
create index analytics_sessions_visitor_idx on public.analytics_sessions (visitor_id);

create table public.analytics_events (
  id               bigint generated always as identity primary key,
  occurred_at      timestamptz not null default now(),
  type             public.analytics_event_type not null,
  visitor_id       uuid not null,
  session_id       uuid not null references public.analytics_sessions (session_id) on delete cascade,
  path             text not null check (path ~ '^/' and char_length(path) <= 512),
  page_type        text not null default 'other' check (page_type in ('home', 'course', 'other')),
  course_id        uuid references public.courses (id) on delete set null,
  target_url       text check (char_length(target_url) <= 2048),        -- outbound_click only
  referrer_domain  text check (referrer_domain ~ '^[a-z0-9.-]{1,253}$'),
  utm_source       text check (char_length(utm_source) <= 100),
  utm_medium       text check (char_length(utm_medium) <= 100),
  utm_campaign     text check (char_length(utm_campaign) <= 100),
  device_type      public.device_type,
  browser          text check (char_length(browser) <= 40),
  os               text check (char_length(os) <= 40),
  country          text check (country ~ '^[A-Z]{2}$'),
  lang             text check (lang in ('en', 'bn')),
  engaged_ms       integer check (engaged_ms between 0 and 86400000)
);
create index analytics_events_occurred_idx on public.analytics_events (occurred_at);
create index analytics_events_course_idx on public.analytics_events (course_id, occurred_at) where course_id is not null;
create index analytics_events_session_idx on public.analytics_events (session_id);
create index analytics_events_path_idx on public.analytics_events (path, occurred_at);

-- Daily rollups (filled by a scheduled job in the analytics phase).
create table public.analytics_daily (
  day                 date primary key,
  visitors            integer not null default 0,
  new_visitors        integer not null default 0,
  returning_visitors  integer not null default 0,
  sessions            integer not null default 0,
  pageviews           integer not null default 0,
  course_views        integer not null default 0,
  avg_engaged_ms      integer not null default 0
);

create table public.analytics_daily_pages (
  day        date not null,
  path       text not null,
  course_id  uuid references public.courses (id) on delete set null,
  views      integer not null default 0,
  visitors   integer not null default 0,
  primary key (day, path)
);

create table public.analytics_daily_dims (
  day        date not null,
  dimension  text not null check (dimension in ('device', 'browser', 'os', 'country', 'source', 'lang')),
  value      text not null,
  visitors   integer not null default 0,
  pageviews  integer not null default 0,
  primary key (day, dimension, value)
);

-- ---------------------------------------------------------------------------
-- RLS: no anonymous access at all; admins read-only; writes = service role.
-- ---------------------------------------------------------------------------
do $$
declare
  t text;
begin
  foreach t in array array[
    'analytics_sessions', 'analytics_events', 'analytics_daily',
    'analytics_daily_pages', 'analytics_daily_dims'
  ] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on public.%I from anon, authenticated', t);
    execute format('grant select on public.%I to authenticated', t);
    execute format(
      'create policy %I on public.%I for select to authenticated using ((select private.is_admin()))',
      t || '_admin_select', t);
  end loop;
end;
$$;

revoke all on sequence public.analytics_events_id_seq from anon, authenticated;

-- >>>>>>>>>>>>>>>>>>>> 20261002090400_storage.sql >>>>>>>>>>>>>>>>>>>>
-- ============================================================================
-- MediVerse Dental CMS — 5/5 Storage
--
-- Bucket "public-media": public READ by URL (served by Supabase's CDN), so
-- flyers / photos / banners load on the website without auth.
-- Listing objects and every write (upload / replace / delete) is admin-only.
-- Only raster images in known folders are accepted (SVG is blocked because it
-- can carry scripts). Max 5 MB per file.
-- ============================================================================

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'public-media', 'public-media', true, 5242880,
  array['image/jpeg', 'image/png', 'image/webp', 'image/avif']
)
on conflict (id) do update
  set public             = excluded.public,
      file_size_limit    = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

-- Helper: is this object path an allowed media location + image extension?
create or replace function private.is_allowed_media_path(p_name text)
returns boolean
language sql
immutable
set search_path = ''
as $$
  select p_name ~ '^(flyers|thumbnails|mentors|banners|logos|images)/[A-Za-z0-9][A-Za-z0-9._-]{0,150}\.(jpe?g|png|webp|avif)$';
$$;
grant execute on function private.is_allowed_media_path(text) to authenticated, service_role;

-- No SELECT policy for anon: visitors fetch files by public URL only and
-- cannot list the bucket.
create policy public_media_admin_select on storage.objects
  for select to authenticated
  using (bucket_id = 'public-media' and (select private.is_admin()));

create policy public_media_admin_insert on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'public-media'
    and (select private.is_admin())
    and private.is_allowed_media_path(name)
  );

create policy public_media_admin_update on storage.objects
  for update to authenticated
  using (bucket_id = 'public-media' and (select private.is_admin()))
  with check (
    bucket_id = 'public-media'
    and (select private.is_admin())
    and private.is_allowed_media_path(name)
  );

create policy public_media_admin_delete on storage.objects
  for delete to authenticated
  using (bucket_id = 'public-media' and (select private.is_admin()));

-- >>>>>>>>>>>>>>>>>>>> seed.sql >>>>>>>>>>>>>>>>>>>>
-- ============================================================================
-- MediVerse Dental CMS — seed data (GENERATED, do not edit by hand)
-- Source: src/build.py, src/template.html, src/i18n_bn.py, assets/
-- Regenerate: python3 mediverse-dental/supabase/seed/generate_seed.py
-- Idempotent only on an empty database (run after `supabase db reset`).
-- ============================================================================


insert into public.media (path, kind, mime, size_bytes, width, height, alt_en, alt_bn, sha256) values
  ('logos/logo-white.png', 'logo', 'image/png', 38993, 500, 260, 'MediVerse Dental logo (white)', null, '00fec8d12d9740db405a9e620dc15e7a3e71fdaa2c9cbf32a0a177fdf75faa3b'),
  ('logos/logo-blue.png', 'logo', 'image/png', 82415, 500, 276, 'MediVerse Dental logo (blue)', null, 'c376e4fcc91422a7438a66cc75595da5c4e61ef65dff2ec543037995e3d3ce25'),
  ('flyers/sdm-full.jpg', 'flyer', 'image/jpeg', 62257, 700, 700, 'SDM Full Course course flyer', null, '7485a25e286117dd74e1c3d9389d9933bfc25412e11b6509cb7db3cb32e884f9'),
  ('flyers/sdm-crash.jpg', 'flyer', 'image/jpeg', 55550, 700, 700, 'SDM Crash Course course flyer', null, '83a8d0ddba78294d7ddccfc3256e13fa202dba0f1e45466faa992d55743b24a3'),
  ('flyers/dental-anatomy.jpg', 'flyer', 'image/jpeg', 47255, 700, 700, 'Dental Anatomy Full Course course flyer', null, '94518fd91fe5f61278ec6857d8b55230a5e5fc84843a33f5a5b234c016e00bd1'),
  ('flyers/anatomy-1.jpg', 'flyer', 'image/jpeg', 69421, 664, 700, 'Anatomy 1st Term course flyer', null, '500121365098ba4fcebee0e3a32fe499ddbb467b1bd0d0f4461485961380725b'),
  ('flyers/anatomy-2.jpg', 'flyer', 'image/jpeg', 84222, 658, 700, 'Anatomy 2nd Term course flyer', null, 'd6ee29151f9edcde1595424c071be566148ec30c1eea96ca114dcf3f3ee21c5e'),
  ('flyers/dental-morphology.jpg', 'flyer', 'image/jpeg', 49072, 597, 700, 'Dental Morphology course flyer', null, '7fb648c41190a5579ac797353d9951a6023fae093e385d7294ffb7f9c8fba770'),
  ('flyers/physiology.jpg', 'flyer', 'image/jpeg', 49737, 615, 700, 'Essential Physiology course flyer', null, '28bf6cf89d942df125f3afa661c19dbc5e1fda29a3b8607b8e2238ae505d9cc7'),
  ('flyers/biochemistry.jpg', 'flyer', 'image/jpeg', 76722, 664, 700, 'Essential Biochemistry course flyer', null, 'a68111e5186ff443a254d623f267bda2118ad95f59ce4d59976cdaa3825e4a58'),
  ('flyers/dental-pharmacology.jpg', 'flyer', 'image/jpeg', 36021, 700, 700, 'Dental Pharmacology course flyer', null, 'cd8736617525b4734590036812ae905bc32f632159a66e9adef8bd78df2b1d6e'),
  ('flyers/pathology.jpg', 'flyer', 'image/jpeg', 42807, 700, 700, 'Essential Pathology for BDS course flyer', null, 'd332537abd995d35ee28d63e20b75d1d576456e66cdb3759553a37238115abc2'),
  ('flyers/microbiology.jpg', 'flyer', 'image/jpeg', 37747, 700, 700, 'Microbiology course flyer', null, '51da140b3001d3dbaa2e34d2e6ada5bb8baeb34004c681e7239a60f4bbf83772'),
  ('flyers/pharmacology.jpg', 'flyer', 'image/jpeg', 28292, 700, 700, 'Pharmacology course flyer', null, 'eb13070f9431b7d2f191dbf1246decf98a3a4c88db7ec98ad713bb8776e9a00b'),
  ('flyers/cc-batch.jpg', 'flyer', 'image/jpeg', 53402, 700, 700, 'C&C — Oral Patho, Medicine & Perio course flyer', null, '93b19a0d35c8f250e056a64aed75fb1a42ca254d5c82dee433289ea11f1825dc'),
  ('flyers/peri-oral-crash.jpg', 'flyer', 'image/jpeg', 67493, 700, 791, 'Crash Course on Peri & Oral Patho course flyer', null, '51f74e0c55129eee39f7c691a83f32f93984d1b4127fb4ddb0ff3c81867a75b9'),
  ('flyers/medicine.jpg', 'flyer', 'image/jpeg', 28485, 700, 700, 'Essential Medicine for BDS course flyer', null, 'b8ce082368c64c714f34272b50ea28b3e075f04ac00ff96086000f40d938890c'),
  ('flyers/surgery.jpg', 'flyer', 'image/jpeg', 72653, 700, 700, 'A Complete Solution of Surgery course flyer', null, 'a58c332fb956b1b4d7ee896b3ffde4a8cc705590b44619d601a1c105a9fca60d'),
  ('flyers/oms.jpg', 'flyer', 'image/jpeg', 50302, 700, 700, 'Mastering Maxillofacial Surgery course flyer', null, 'd072202ee30c08bb63fc1b416670d680e91ae884fe0d423a0df9bc5bd4fff95a'),
  ('flyers/conservative.jpg', 'flyer', 'image/jpeg', 44871, 700, 700, 'Conservative & Endo Core Course course flyer', null, '3a97ceeefe4558350be468657a6f47c1e37deaf4713dd808fd988a0bcc242c3e'),
  ('flyers/orthodontics.jpg', 'flyer', 'image/jpeg', 67094, 664, 700, 'Orthodontics Made Easy course flyer', null, 'd71a5985731a76121ad8d779628fa30b5c634183f22a5b5cdc1cbe0793227e8a'),
  ('flyers/decode-opg.jpg', 'flyer', 'image/jpeg', 66251, 663, 700, 'Decode the OPG course flyer', null, 'eb2afe45e5a95fa7fd931e32ab24f24741bef5948c9af443028a412d34b14503'),
  ('flyers/prosthodontics.jpg', 'flyer', 'image/jpeg', 54890, 700, 700, 'Prosthodontics Made Easy course flyer', null, '292d04eb5f0c2ca49910ab7be74a5a70146b217d9d714f48bbcb81bcf6c23035'),
  ('mentors/tanim.jpg', 'mentor_photo', 'image/jpeg', 133452, 861, 1148, 'Dr. Tanim Ahmed', null, '330e41f6c09dcbc2e375331748968d139348de8f3d7865f4684313cfbba2b827'),
  ('mentors/sifat.jpg', 'mentor_photo', 'image/jpeg', 83735, 810, 1080, 'Dr. M R Sifat', null, '0529bebdb12a3fc785fd93fe99d018811a7c3c68f171826129fb1f68bb9db292'),
  ('mentors/fahim.jpg', 'mentor_photo', 'image/jpeg', 194832, 900, 1200, 'Firoj Ahamed Fahim', null, '4c50d3d0d4251a3545da267b55487a0217cc82c2e99fcad633267a082de20d8f'),
  ('mentors/munir.jpg', 'mentor_photo', 'image/jpeg', 165211, 900, 1200, 'Sirajum Munir', null, 'a8be4e1fede5fad4ff95d3296a7fb98229abbe1dd7543badc3bbc8e1e3d1ae6b'),
  ('mentors/adlul.jpg', 'mentor_photo', 'image/jpeg', 133327, 900, 1200, 'Khondkar Adlul Haque', null, 'f6c5eb34a935491f1066d1280cfa04af4fe8ee410019134396f83dbea08c3f99'),
  ('mentors/siyam.jpg', 'mentor_photo', 'image/jpeg', 102863, 807, 1076, 'Dr. Mahmudul Hasan Siyam', null, '44d56f1d0d26e952a8228402617cc3948f5a84a530cf4c435ac98ac514a4ff17');

insert into public.site_settings (site_name, logo_dark_media_id, logo_light_media_id, seo_title_en, seo_title_bn, seo_description_en, seo_description_bn, whatsapp_number, whatsapp_message_en, copyright_en, copyright_bn, footer_tagline_en, footer_tagline_bn, primary_cta_url) values
  ('MediVerse Dental', (select id from public.media where path = 'logos/logo-white.png'), (select id from public.media where path = 'logos/logo-blue.png'), 'MediVerse Dental — Future Dentistry Begins Here', 'মেডিভার্স ডেন্টাল — ডেন্টিস্ট্রির ভবিষ্যৎ শুরু এখান থেকেই', 'MediVerse Dental — phase-wise BDS courses, expert mentors and exam-focused notes for dental students across Bangladesh.', 'ফেজ ধরে সাজানো BDS কোর্স, অভিজ্ঞ মেন্টর আর পরীক্ষার নোটস — বাংলাদেশের ডেন্টাল স্টুডেন্টদের জন্য।', '+8801726415926', 'Hello MediVerse Dental, I would like to know more about your BDS courses.', 'MediVerse Dental. All rights reserved.', 'মেডিভার্স ডেন্টাল। সর্বস্বত্ব সংরক্ষিত।', 'Made for BDS students, by expert mentors 🦷', 'BDS স্টুডেন্টদের জন্য, এক্সপার্ট মেন্টরদের হাতে বানানো 🦷', 'https://mediversebd.com');

insert into public.phases (code, name_en, name_bn, summary_en, summary_bn, sort_order) values
  (1, '1st Phase', '১ম ফেজ', 'SDM, Dental Anatomy, Physiology, Biochemistry — the foundation, with diagram-heavy notes and viva prep.', 'SDM, Dental Anatomy, Physiology, Biochemistry — বেসটা এখানেই শক্ত হয়। সাথে ডায়াগ্রামসহ নোটস আর ভাইভা প্রস্তুতি।', 10),
  (2, '2nd Phase', '২য় ফেজ', 'Pharmacology, Pathology, Microbiology — dense subjects distilled into exam-ready summaries.', 'Pharmacology, Pathology, Microbiology — ভারী ভারী সাবজেক্টগুলো ছোট করে, পরীক্ষার উপযোগী করে গুছিয়ে দেওয়া।', 20),
  (3, '3rd Phase', '৩য় ফেজ', 'Oral Pathology & Medicine, Periodontology, Medicine, Surgery — where clinical thinking takes shape.', 'Oral Pathology & Medicine, Periodontology, Medicine, Surgery — এখান থেকেই ক্লিনিক্যালি ভাবতে শেখা শুরু।', 30),
  (4, 'Final Phase', 'ফাইনাল ফেজ', 'OMS, Conservative, Orthodontics, Prosthodontics, Pedodontics — mastery for finals.', 'OMS, Conservative, Orthodontics, Prosthodontics, Pedodontics — ফাইনালের পুরো প্রস্তুতি।', 40);

insert into public.courses (slug, title_en, title_bn, short_desc_en, short_desc_bn, phase_id, flyer_media_id, external_url, cta_label_en, cta_label_bn, search_keywords, status, sort_order) values
  ('sdm-full-course', 'SDM Full Course', null, 'Complete Science of Dental Materials, exam-mapped from the start.', 'পুরো Science of Dental Materials — শুরু থেকেই পরীক্ষার কথা মাথায় রেখে সাজানো।', (select id from public.phases where code = 1), (select id from public.media where path = 'flyers/sdm-full.jpg'), 'https://mediversebd.com/courses/science-of-dental-materials-full-course', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['science', 'of', 'dental', 'materials']::text[], 'active', 10),
  ('sdm-crash-course', 'SDM Crash Course', null, 'A fast, exam-focused refresher covering SDM''s high-yield topics.', 'SDM-এর ইম্পর্ট্যান্ট টপিকগুলোর ঝটপট রিভিশন — পরীক্ষার ঠিক আগে কাজে লাগবে।', (select id from public.phases where code = 1), (select id from public.media where path = 'flyers/sdm-crash.jpg'), 'https://mediversebd.com/courses/sdm-crash-course', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['science', 'of', 'dental', 'materials', 'revision']::text[], 'active', 20),
  ('dental-anatomy-full-course', 'Dental Anatomy Full Course', null, 'Tooth morphology through full arch relations and occlusion.', 'দাঁতের মরফোলজি থেকে শুরু করে ফুল আর্চ রিলেশন আর অক্লুশন পর্যন্ত।', (select id from public.phases where code = 1), (select id from public.media where path = 'flyers/dental-anatomy.jpg'), 'https://mediversebd.com/courses/dental-anatomy-full-course', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['da', 'tooth', 'morphology']::text[], 'active', 30),
  ('anatomy-1st-term', 'Anatomy 1st Term', null, 'Foundational general anatomy, structured for early BDS.', 'BDS-এর শুরুতে জেনারেল অ্যানাটমির বেসটা শক্ত করার কোর্স।', (select id from public.phases where code = 1), (select id from public.media where path = 'flyers/anatomy-1.jpg'), 'https://mediversebd.com/courses/anatomy-first-term-for-bds', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['general', 'anatomy']::text[], 'active', 40),
  ('anatomy-2nd-term', 'Anatomy 2nd Term', null, 'Continues core anatomy with viva-focused revision notes.', 'অ্যানাটমির বাকি অংশ, সাথে ভাইভার জন্য রিভিশন নোটস।', (select id from public.phases where code = 1), (select id from public.media where path = 'flyers/anatomy-2.jpg'), 'https://mediversebd.com/courses/anatomy-second-term-for-bds', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['general', 'anatomy']::text[], 'active', 50),
  ('dental-morphology', 'Dental Morphology', null, 'Tooth form and function, mapped for practical and theory exams.', 'দাঁতের গঠন আর কাজ — প্র্যাকটিক্যাল আর থিওরি, দুই পরীক্ষার জন্যই।', (select id from public.phases where code = 1), (select id from public.media where path = 'flyers/dental-morphology.jpg'), 'https://mediversebd.com/courses/dental-morphology', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['tooth', 'anatomy']::text[], 'active', 60),
  ('essential-physiology', 'Essential Physiology', null, 'Systems-based physiology notes built for BDS first phase.', 'সিস্টেম ধরে ধরে ফিজিওলজি নোটস, BDS ফার্স্ট ফেজের জন্য বানানো।', (select id from public.phases where code = 1), (select id from public.media where path = 'flyers/physiology.jpg'), 'https://mediversebd.com/courses/essential-physiology-for-bds', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', '{}'::text[], 'active', 70),
  ('essential-biochemistry', 'Essential Biochemistry', null, 'Core biochemical concepts, simplified for dental students.', 'বায়োকেমিস্ট্রির মূল কনসেপ্টগুলো, ডেন্টাল স্টুডেন্টদের জন্য সহজ করে।', (select id from public.phases where code = 1), (select id from public.media where path = 'flyers/biochemistry.jpg'), 'https://mediversebd.com/courses/essential-biochemistry-for-bds', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', '{}'::text[], 'active', 80),
  ('dental-pharmacology', 'Dental Pharmacology', null, 'Drug classes and dental prescriptions, exam-focused.', 'ড্রাগের ক্লাস আর ডেন্টাল প্রেসক্রিপশন — পরীক্ষায় যেভাবে আসে, সেভাবেই।', (select id from public.phases where code = 2), (select id from public.media where path = 'flyers/dental-pharmacology.jpg'), 'https://mediversebd.com/courses/dental-pharmacology', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['drugs', 'prescription']::text[], 'active', 90),
  ('essential-pathology-for-bds', 'Essential Pathology for BDS', null, 'Concept-first notes on inflammation, neoplasia and healing.', 'ইনফ্লামেশন, নিওপ্লাসিয়া, হিলিং — আগে কনসেপ্ট পরিষ্কার, তারপর নোটস।', (select id from public.phases where code = 2), (select id from public.media where path = 'flyers/pathology.jpg'), 'https://mediversebd.com/courses/essential-pathology-for-bds', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['general', 'pathology']::text[], 'active', 100),
  ('microbiology', 'Microbiology', null, 'Organism-wise notes built around board-relevant clinical links.', 'অর্গানিজম ধরে ধরে নোটস, সাথে পরীক্ষায় আসা ক্লিনিক্যাল কানেকশন।', (select id from public.phases where code = 2), (select id from public.media where path = 'flyers/microbiology.jpg'), 'https://mediversebd.com/courses/microbiology-full-course', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['micro']::text[], 'active', 110),
  ('pharmacology', 'Pharmacology', null, 'General pharmacology principles ahead of dental applications.', 'জেনারেল ফার্মাকোলজির বেসিক — ডেন্টাল ফার্মাকোলজিতে ঢোকার আগে।', (select id from public.phases where code = 2), (select id from public.media where path = 'flyers/pharmacology.jpg'), 'https://mediversebd.com/courses/pharmacology-full-course', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['drugs']::text[], 'active', 120),
  ('c-and-c-oral-patho-medicine-and-perio', 'C&C — Oral Patho, Medicine & Perio', null, 'Combined Oral Pathology, Oral Medicine and Periodontology.', 'Oral Pathology, Oral Medicine আর Periodontology — এক কোর্সেই।', (select id from public.phases where code = 3), (select id from public.media where path = 'flyers/cc-batch.jpg'), 'https://mediversebd.com/courses/cawson-carranza', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['cawson', 'carranza', 'oral', 'pathology', 'periodontology']::text[], 'active', 130),
  ('crash-course-on-peri-and-oral-patho', 'Crash Course on Peri & Oral Patho', null, 'Question-based rapid revision of Periodontology and Oral Pathology for written and viva.', 'প্রফের প্রশ্ন ধরে Periodontology আর Oral Pathology-র ঝটপট রিভিশন — লিখিত আর ভাইভা দুটোর জন্যই।', (select id from public.phases where code = 3), (select id from public.media where path = 'flyers/peri-oral-crash.jpg'), 'https://mediversebd.com/courses/crash-course-on-peri-oral-patho', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['cawson', 'carranza', 'perio', 'periodontology', 'oral', 'pathology', 'crash', 'revision']::text[], 'active', 140),
  ('essential-medicine-for-bds', 'Essential Medicine for BDS', null, 'Core general medicine concepts relevant to dental practice and exams.', 'ডেন্টাল প্র্যাকটিস আর পরীক্ষায় যতটুকু মেডিসিন লাগে, ঠিক ততটুকু।', (select id from public.phases where code = 3), (select id from public.media where path = 'flyers/medicine.jpg'), 'https://mediversebd.com/courses/essential-medicine-for-bds', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['general', 'medicine']::text[], 'active', 150),
  ('a-complete-solution-of-surgery', 'A Complete Solution of Surgery', null, 'Full prep for Surgery Paper I — written, viva, OSPE, long and short cases.', 'সার্জারি পেপার ওয়ানের পুরো প্রস্তুতি — লিখিত, ভাইভা, OSPE, লং কেস আর শর্ট কেস।', (select id from public.phases where code = 3), (select id from public.media where path = 'flyers/surgery.jpg'), 'https://mediversebd.com/courses/a-complete-solution-of-surgery', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['general', 'surgery', 'ospe', 'long', 'case', 'short', 'case']::text[], 'active', 160),
  ('mastering-maxillofacial-surgery', 'Mastering Maxillofacial Surgery', null, 'OMS concepts through to exam-format short and long cases.', 'OMS-এর কনসেপ্ট থেকে শুরু করে পরীক্ষার মতো করে শর্ট আর লং কেস।', (select id from public.phases where code = 4), (select id from public.media where path = 'flyers/oms.jpg'), 'https://mediversebd.com/courses/maxillofacial-surgery', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['oms', 'oral', 'surgery']::text[], 'active', 170),
  ('conservative-and-endo-core-course', 'Conservative & Endo Core Course', null, 'Cavity classification through endodontic protocols, simplified.', 'ক্যাভিটি ক্লাসিফিকেশন থেকে এন্ডোডন্টিক প্রোটোকল — সহজ ভাষায়।', (select id from public.phases where code = 4), (select id from public.media where path = 'flyers/conservative.jpg'), 'https://mediversebd.com/courses/conservative-endodontics', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['endodontics', 'operative']::text[], 'active', 180),
  ('orthodontics-made-easy', 'Orthodontics Made Easy', null, 'Core orthodontic concepts distilled for finals revision.', 'অর্থোডন্টিক্সের জরুরি কনসেপ্টগুলো, ফাইনালের রিভিশনের জন্য বেছে আনা।', (select id from public.phases where code = 4), (select id from public.media where path = 'flyers/orthodontics.jpg'), 'https://mediversebd.com/courses/orthodontics-made-easy', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['ortho']::text[], 'active', 190),
  ('decode-the-opg', 'Decode the OPG', null, 'Step-by-step OPG, PNS and OM view interpretation with real cases.', 'রিয়েল কেস দেখে দেখে ধাপে ধাপে OPG, PNS আর OM ভিউ পড়া শেখো।', (select id from public.phases where code = 4), (select id from public.media where path = 'flyers/decode-opg.jpg'), 'https://mediversebd.com/courses/decode-the-opg', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['radiology', 'x-ray', 'opg']::text[], 'active', 200),
  ('prosthodontics-made-easy', 'Prosthodontics Made Easy', null, 'Removable and fixed prosthodontics, exam-focused summaries.', 'রিমুভেবল আর ফিক্সড প্রস্থোডন্টিক্স — পরীক্ষার জন্য গোছানো সামারি।', (select id from public.phases where code = 4), (select id from public.media where path = 'flyers/prosthodontics.jpg'), 'https://mediversebd.com/courses/prosthodontics-made-easy', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['prostho', 'denture']::text[], 'active', 210),
  ('pedodontics-made-easy', 'Pedodontics Made Easy', null, 'Child dental care and management, simplified for finals.', 'বাচ্চাদের ডেন্টাল কেয়ার আর ম্যানেজমেন্ট, ফাইনালের জন্য সহজ করে।', (select id from public.phases where code = 4), null, 'https://mediversebd.com', 'Enroll on Mediverse', 'মেডিভার্সে এনরোল করো', array['paediatric', 'pediatric', 'children']::text[], 'active', 220);

insert into public.mentors (slug, name, designation_en, designation_bn, credentials, session, photo_media_id, avatar_style, status, sort_order) values
  ('tanim-ahmed', 'Dr. Tanim Ahmed', 'Oral Patho · Perio · OMS · Conservative', null, 'MDCH, Session 2018-19. Expertise: Oral Pathology & Medicine, Periodontology, Oral & Maxillofacial Surgery, Conservative & Endodontics.', '2018-19', (select id from public.media where path = 'mentors/tanim.jpg'), 'photo', 'active', 10),
  ('m-r-sifat', 'Dr. M R Sifat', 'Medicine', null, 'MBBS (DMC), BCS (Health), FCPS P-1 (Medicine), MRCP P-2 (UK). DMC, Session 2014-15.', '2014-15', (select id from public.media where path = 'mentors/sifat.jpg'), 'photo', 'active', 20),
  ('firoj-ahamed-fahim', 'Firoj Ahamed Fahim', 'SDM & Dental Anatomy', null, 'Final year BDS, Sir Salimullah Medical College (Dental Unit), Session 2021-22.', '2021-22', (select id from public.media where path = 'mentors/fahim.jpg'), 'photo', 'active', 30),
  ('sirajum-munir', 'Sirajum Munir', 'General Anatomy', null, 'Pioneer Dental College (PDC), Session 2023-24.', '2023-24', (select id from public.media where path = 'mentors/munir.jpg'), 'photo', 'active', 40),
  ('khondkar-adlul-haque', 'Khondkar Adlul Haque', 'Biochemistry', null, 'Pioneer Dental College (PDC), Session 2023-24.', '2023-24', (select id from public.media where path = 'mentors/adlul.jpg'), 'photo', 'active', 50),
  ('nusrat-jahan-efty', 'Nusrat Jahan Efty', 'Dental Pharmacology', null, 'Sir Salimullah Medical College, Session 2021-22.', '2021-22', null, 'hijab_icon', 'active', 60),
  ('mahmudul-hasan-siyam', 'Dr. Mahmudul Hasan Siyam', 'Prosthodontics', null, 'SSMC, DU. Session 2018-19.', '2018-19', (select id from public.media where path = 'mentors/siyam.jpg'), 'photo', 'active', 70),
  ('faiza-tabassum', 'Dr. Faiza Tabassum', 'Orthodontics', null, 'FCPS Part II Trainee (Dhaka Dental College), Session 2017-18. 3rd in BDS Final Prof (DU). Honours in OMS, Orthodontics, Prosthodontics, Conservative, General Surgery and Dental Anatomy.', '2017-18', null, 'hijab_icon', 'active', 80),
  ('taslima-jahan-lubna', 'Dr. Taslima Jahan Lubna', 'Orthodontics', null, 'Marks Dental College, Session 2010-11. Pursuing MFDS RCSEng Part-1 and FCPS Part-1 (Orthodontics).', '2010-11', null, 'hijab_icon', 'active', 90),
  ('jannatul-ferdous', 'Dr. Jannatul Ferdous', 'Conservative & Endo', null, 'IMC, Session 2014-15. MS at BMU (Conservative Dentistry & Endodontics). Honours in Dental Public Health and Medicine.', '2014-15', null, 'hijab_icon', 'active', 100);

insert into public.course_mentors (course_id, mentor_id, role) values
  ((select id from public.courses where slug = 'sdm-full-course'), (select id from public.mentors where slug = 'firoj-ahamed-fahim'), 'lead'),
  ((select id from public.courses where slug = 'sdm-crash-course'), (select id from public.mentors where slug = 'firoj-ahamed-fahim'), 'lead'),
  ((select id from public.courses where slug = 'dental-anatomy-full-course'), (select id from public.mentors where slug = 'firoj-ahamed-fahim'), 'lead'),
  ((select id from public.courses where slug = 'anatomy-1st-term'), (select id from public.mentors where slug = 'sirajum-munir'), 'lead'),
  ((select id from public.courses where slug = 'c-and-c-oral-patho-medicine-and-perio'), (select id from public.mentors where slug = 'tanim-ahmed'), 'lead'),
  ((select id from public.courses where slug = 'crash-course-on-peri-and-oral-patho'), (select id from public.mentors where slug = 'tanim-ahmed'), 'lead'),
  ((select id from public.courses where slug = 'essential-medicine-for-bds'), (select id from public.mentors where slug = 'm-r-sifat'), 'lead');

insert into public.page_sections (key, sort_order, is_visible, content) values
  ('hero', 10, true, '{"en": {"kicker": "BDS Education · Built for Bangladesh", "heading": "Future Dentistry\n[[Begins Here.]]", "tagline": "ডেন্টাল শিক্ষার নতুন দিগন্ত", "lead": "Phase-wise BDS courses, expert mentors and exam-focused notes — everything a dental student in Bangladesh needs, on one modern platform."}, "bn": {"kicker": "BDS-এর পড়াশোনা · বাংলাদেশের জন্য", "heading": "ডেন্টিস্ট্রির ভবিষ্যৎ\n[[শুরু এখান থেকেই।]]", "tagline": "ডেন্টাল শিক্ষার নতুন দিগন্ত", "lead": "ফেজ ধরে সাজানো BDS কোর্স, অভিজ্ঞ মেন্টর আর পরীক্ষায় সত্যিই কাজে লাগে এমন নোটস — একজন ডেন্টাল স্টুডেন্টের যা যা লাগে, সব এক জায়গায়।"}, "buttons": [{"label_en": "Explore Courses", "label_bn": "কোর্সগুলো দেখো", "url": "#courses", "style": "primary", "new_tab": false}, {"label_en": "Meet the Mentors", "label_bn": "মেন্টরদের চেনো", "url": "#mentors", "style": "ghost", "new_tab": false}]}'::jsonb),
  ('about', 20, true, '{"en": {"kicker": "About MediVerse Dental", "heading": "Dental education, [[re-engineered]] for how you actually study.", "intro": "MediVerse Dental is an academic platform built by expert mentors to help BDS students learn better, prepare smarter and access quality resources — wherever they are in Bangladesh.", "mission_heading": "Our goal is simple — make quality dental education accessible, structured and easier to learn.", "mission_body": "From 1st Prof SDM to Final Prof OMS, every course is mapped to the BDS curriculum and standard textbooks, taught by mentors who have sat the same exams you''re preparing for.", "trust_line": "Trusted by **4,700+ BDS students** from dental colleges nationwide", "highlight_value": "25+", "highlight_label": "Courses covering every BDS professional phase"}, "bn": {"kicker": "মেডিভার্স ডেন্টাল আসলে কী?", "heading": "ডেন্টালের পড়া, [[তোমার মতো করে]] সাজানো।", "intro": "মেডিভার্স ডেন্টাল হলো BDS স্টুডেন্টদের জন্য একটা অনলাইন পড়াশোনার প্ল্যাটফর্ম। ঢাকায় থাকো বা দেশের যেকোনো জায়গায় — বুঝে পড়া, গুছিয়ে প্রস্তুতি নেওয়া আর ভালো রিসোর্স হাতের কাছে পাওয়া, সবই এখানে।", "mission_heading": "আমাদের চাওয়াটা খুব সোজা — ভালো মানের ডেন্টাল পড়াশোনা যেন সবার নাগালে থাকে, গোছানো থাকে, আর পড়তে গিয়ে ঝামেলা না লাগে।", "mission_body": "ফার্স্ট প্রফের SDM থেকে ফাইনাল প্রফের OMS — প্রতিটা কোর্স BDS সিলেবাস আর স্ট্যান্ডার্ড টেক্সটবুক মেনে বানানো। পড়ান সেই মেন্টররা, যারা নিজেরাই এই পরীক্ষাগুলো পার করে এসেছেন।", "trust_line": "দেশের নানা ডেন্টাল কলেজের **৪,৭০০+ স্টুডেন্ট** আমাদের সাথে পড়ছে", "highlight_value": "২৫+", "highlight_label": "কোর্স — BDS-এর প্রতিটা প্রফের জন্য"}, "buttons": []}'::jsonb),
  ('courses', 30, true, '{"en": {"kicker": "Courses", "heading": "Find the course for [[your phase]].", "intro": "Filter by professional phase or search a subject — every course is built from board-relevant textbooks and exam patterns.", "search_placeholder": "Search e.g. OPG, Anatomy, Ortho…"}, "bn": {"kicker": "কোর্স", "heading": "[[তোমার ফেজের]] কোর্সটা খুঁজে নাও।", "intro": "ফেজ বেছে নাও, নয়তো সাবজেক্টের নাম লিখে সার্চ করো — প্রতিটা কোর্স টেক্সটবুক আর প্রফের প্রশ্নের ধরন মেনে বানানো।", "search_placeholder": "সার্চ করো, যেমন OPG, Anatomy, Ortho…"}, "buttons": [{"label_en": "See all courses on mediversebd.com", "label_bn": "সব কোর্স দেখো mediversebd.com-এ", "url": "https://mediversebd.com", "style": "ghost", "new_tab": true}]}'::jsonb),
  ('mentors', 40, true, '{"en": {"kicker": "Expert Mentor Panel", "heading": "Learn from expert mentors who''ve [[sat where you''re sitting]].", "intro": "15+ mentors from DMC, DDC, SSMC, MDCH, IMC and more — toppers, FCPS trainees and practising clinicians."}, "bn": {"kicker": "এক্সপার্ট মেন্টর প্যানেল", "heading": "শেখো তাদের কাছে, [[যারা একদিন তোমার জায়গাতেই ছিলেন]]।", "intro": "DMC, DDC, SSMC, MDCH, IMC সহ দেশের নানা কলেজের ১৫+ মেন্টর — কেউ প্রফে টপার, কেউ FCPS ট্রেইনি, কেউ প্র্যাকটিসিং ক্লিনিশিয়ান।"}, "buttons": []}'::jsonb),
  ('stories', 50, true, '{"en": {"kicker": "Student stories", "heading": "What students say after [[MediVerse]]."}, "bn": {"kicker": "স্টুডেন্টদের কথা", "heading": "[[মেডিভার্স]] নিয়ে স্টুডেন্টরা কী বলছে"}, "buttons": []}'::jsonb),
  ('faq', 60, true, '{"en": {"kicker": "FAQ", "heading": "Questions? [[Answered.]]", "intro": "Can''t find what you need? Message us on WhatsApp or Telegram — the MediVerse team usually replies within a few hours."}, "bn": {"kicker": "প্রশ্ন-উত্তর", "heading": "মনে প্রশ্ন? [[উত্তর এখানেই।]]", "intro": "যা খুঁজছ পাচ্ছ না? হোয়াটসঅ্যাপ বা টেলিগ্রামে নক দাও — সাধারণত কয়েক ঘণ্টার মধ্যেই রিপ্লাই পেয়ে যাবে।"}, "buttons": []}'::jsonb),
  ('contact', 70, true, '{"en": {"heading": "Ready to study smarter this term?", "body": "Join thousands of BDS students already learning with MediVerse Dental. Talk to our team or jump straight into a course."}, "bn": {"heading": "এই টার্মে স্মার্টলি পড়তে রেডি?", "body": "হাজারো BDS স্টুডেন্ট এখন মেডিভার্স ডেন্টালে পড়ছে। কিছু জানার থাকলে আমাদের সাথে কথা বলো, নয়তো সরাসরি কোর্সে ঢুকে পড়ো।"}, "buttons": [{"label_en": "Start Learning", "label_bn": "পড়া শুরু করো", "url": "https://mediversebd.com", "style": "primary", "new_tab": true}, {"label_en": "Chat on WhatsApp", "label_bn": "হোয়াটসঅ্যাপে কথা বলো", "url": "https://wa.me/8801726415926?text=Hello%20MediVerse%20Dental%2C%20I%20would%20like%20to%20know%20more%20about%20your%20BDS%20courses.", "style": "ghost", "new_tab": true}]}'::jsonb);

insert into public.stats (value, suffix, label_en, label_bn, sort_order) values
  (4700, '+', 'Students reached', 'স্টুডেন্ট আমাদের সাথে', 10),
  (25, '+', 'Academic courses', 'কোর্স', 20),
  (15, '+', 'Expert mentors', 'এক্সপার্ট মেন্টর', 30),
  (100, '+', 'Free classes', 'ফ্রি ক্লাস', 40);

insert into public.features (icon, title_en, title_bn, body_en, body_bn, sort_order) values
  ('video', 'Recorded + live classes', 'রেকর্ডেড + লাইভ ক্লাস', 'Learn at your pace with HD recordings, then clear doubts in live sessions.', 'রেকর্ডেড ক্লাস দেখো নিজের সময়মতো, আর যেটা বুঝবে না — লাইভে এসে জিজ্ঞেস করে নাও।', 10),
  ('notes', 'Exam-mapped notes', 'পরীক্ষা মাথায় রেখে নোটস', 'Diagram-heavy class notes, viva prep and question practice built for BDS profs.', 'ডায়াগ্রাম দিয়ে বোঝানো নোটস, ভাইভার প্রস্তুতি আর প্রশ্ন সলভ — সবই প্রফের কথা ভেবে।', 20),
  ('chat', '24/7 mentor support', '২৪/৭ মেন্টর সাপোর্ট', 'Chatbox support and a mentor panel that actually replies to your questions.', 'চ্যাটবক্সে যখন খুশি প্রশ্ন করো — মেন্টররা সত্যিই উত্তর দেন।', 30);

insert into public.faqs (question_en, question_bn, answer_en, answer_bn, sort_order) values
  ('How do I enroll in a course?', 'কোর্সে এনরোল করব কীভাবে?', 'Open the course page on [mediversebd.com](https://mediversebd.com), tap Enroll and complete payment (bKash / Nagad / card). You get access in your dashboard right away.', '[mediversebd.com](https://mediversebd.com)-এ গিয়ে কোর্সটা খোলো, Enroll-এ চাপ দাও, তারপর বিকাশ / নগদ / কার্ডে পেমেন্ট করে ফেলো। পেমেন্ট হলেই কোর্স তোমার ড্যাশবোর্ডে চলে আসবে।', 10),
  ('Are classes live or recorded?', 'ক্লাস কি লাইভ, নাকি রেকর্ডেড?', 'Both. Core lectures are recorded so you can study at your own pace; live sessions and doubt-clearing classes are announced on our Facebook group and Telegram channel.', 'দুটোই। মূল ক্লাসগুলো রেকর্ডেড, তাই নিজের সুবিধামতো দেখতে পারবে। লাইভ ক্লাস আর ডাউট সলভিং সেশনের আপডেট পাবে আমাদের ফেসবুক গ্রুপ আর টেলিগ্রাম চ্যানেলে।', 20),
  ('How long do I keep access?', 'কোর্স কতদিন দেখা যাবে?', 'Most full courses give you access for up to 2 years — long enough to revise before your professional exam. Check each course page for exact duration.', 'বেশিরভাগ ফুল কোর্সে ২ বছর পর্যন্ত অ্যাক্সেস থাকে — প্রফের আগে রিভিশন দেওয়ার জন্য যথেষ্ট সময়। কোন কোর্সের মেয়াদ কত, সেটা কোর্স পেজেই লেখা আছে।', 30),
  ('Can I watch on my phone?', 'মোবাইল থেকে ক্লাস করা যাবে?', 'Yes. The platform is website-based and works on any phone, tablet or laptop browser — no app install needed. Bookmarking lets you jump back to where you left off.', 'অবশ্যই। কোনো অ্যাপ নামাতে হবে না — ফোন, ট্যাব বা ল্যাপটপের ব্রাউজার থেকেই চলবে। বুকমার্ক করে রাখলে যেখানে থেমেছিলে, পরে ঠিক সেখান থেকেই শুরু করতে পারবে।', 40),
  ('Do you offer free classes?', 'ফ্রি ক্লাস আছে?', 'Yes — 100+ free classes are on our YouTube channel. Subscribe to [@mediversedental](https://youtube.com/@mediversedental?si=VuCm4kPuqcdEORaJ) to get notified.', 'আছে! আমাদের ইউটিউব চ্যানেলে ১০০+ ফ্রি ক্লাস আছে। নতুন ক্লাসের আপডেট পেতে [@mediversedental](https://youtube.com/@mediversedental?si=VuCm4kPuqcdEORaJ) সাবস্ক্রাইব করে রাখো।', 50);

insert into public.testimonials (quote_en, quote_bn, attribution_en, attribution_bn, source_en, source_bn, sort_order) values
  ('The SDM notes were exactly what came in my viva. I didn''t need any other book that term.', 'SDM-এর নোটসে যা ছিল, ভাইভায় হুবহু সেগুলোই ধরেছে। ওই টার্মে আর অন্য কোনো বই খুলতেই হয়নি।', '3rd Prof student', 'থার্ড প্রফের স্টুডেন্ট', 'Dhaka Dental College', 'ঢাকা ডেন্টাল কলেজ', 10),
  ('Having a mentor actually reply to my questions changed how I studied for finals.', 'প্রশ্ন করলে মেন্টর সত্যি সত্যিই উত্তর দিতেন — ফাইনালের আগে আমার পড়ার ধরনটাই বদলে গেছে।', '4th Prof student', 'ফোর্থ প্রফের স্টুডেন্ট', 'Chattagram Dental College', 'চট্টগ্রাম ডেন্টাল কলেজ', 20),
  ('The OMS case book format matches the exam so closely it felt like practice runs.', 'OMS কেস বুকের ফরম্যাট পরীক্ষার সাথে এত মিলে যায় যে মনে হচ্ছিল আগেই একবার পরীক্ষা দিয়ে ফেলেছি।', 'Final Prof student', 'ফাইনাল প্রফের স্টুডেন্ট', 'BDS, Bangladesh', 'BDS, বাংলাদেশ', 30);

insert into public.nav_items (location, label_en, label_bn, url, is_external, open_new_tab, style, sort_order) values
  ('header', 'About', 'আমাদের কথা', '#about', false, false, 'link', 10),
  ('header', 'Courses', 'কোর্স', '#courses', false, false, 'link', 20),
  ('header', 'Mentors', 'মেন্টর', '#mentors', false, false, 'link', 30),
  ('header', 'Stories', 'রিভিউ', '#stories', false, false, 'link', 40),
  ('header', 'FAQ', 'প্রশ্ন-উত্তর', '#faq', false, false, 'link', 50),
  ('header', 'Enroll Now', 'এনরোল করো', 'https://mediversebd.com', true, true, 'button', 60),
  ('mobile', 'Home', 'হোম', '#top', false, false, 'link', 10),
  ('mobile', 'About MediVerse', 'মেডিভার্স সম্পর্কে', '#about', false, false, 'link', 20),
  ('mobile', 'Courses', 'কোর্স', '#courses', false, false, 'link', 30),
  ('mobile', 'Mentor Panel', 'মেন্টর প্যানেল', '#mentors', false, false, 'link', 40),
  ('mobile', 'Student Stories', 'স্টুডেন্টদের রিভিউ', '#stories', false, false, 'link', 50),
  ('mobile', 'FAQ & Contact', 'প্রশ্ন-উত্তর ও যোগাযোগ', '#faq', false, false, 'link', 60),
  ('mobile', 'Enroll at mediversebd.com', 'mediversebd.com-এ এনরোল করো', 'https://mediversebd.com', true, true, 'button', 70);

insert into public.footer_sections (type, title_en, title_bn, body_en, body_bn, sort_order) values
  ('text', null, null, 'Future Dentistry Begins Here. A BDS education platform guided by expert mentors — phase-wise courses, mentor guidance and exam-focused notes for students across Bangladesh.', 'ডেন্টিস্ট্রির ভবিষ্যৎ শুরু এখান থেকেই। এক্সপার্ট মেন্টরদের হাতে গড়া BDS পড়াশোনার প্ল্যাটফর্ম — সারা দেশের স্টুডেন্টদের জন্য ফেজ অনুযায়ী কোর্স, মেন্টরের গাইডলাইন আর পরীক্ষার নোটস।', 10),
  ('links', 'Courses', 'কোর্স', null, null, 20),
  ('links', 'Explore', 'ঘুরে দেখো', null, null, 30),
  ('links', 'Platform', 'প্ল্যাটফর্ম', null, null, 40);

insert into public.footer_links (section_id, label_en, label_bn, url, is_external, sort_order) values
  ((select id from public.footer_sections where title_en = 'Courses'), '1st Phase', '১ম ফেজ', '#phase-1', false, 10),
  ((select id from public.footer_sections where title_en = 'Courses'), '2nd Phase', '২য় ফেজ', '#phase-2', false, 20),
  ((select id from public.footer_sections where title_en = 'Courses'), '3rd Phase', '৩য় ফেজ', '#phase-3', false, 30),
  ((select id from public.footer_sections where title_en = 'Courses'), 'Final Phase', 'ফাইনাল ফেজ', '#phase-4', false, 40),
  ((select id from public.footer_sections where title_en = 'Explore'), 'About', 'আমাদের কথা', '#about', false, 10),
  ((select id from public.footer_sections where title_en = 'Explore'), 'Mentor Panel', 'মেন্টর প্যানেল', '#mentors', false, 20),
  ((select id from public.footer_sections where title_en = 'Explore'), 'Student Stories', 'স্টুডেন্টদের রিভিউ', '#stories', false, 30),
  ((select id from public.footer_sections where title_en = 'Explore'), 'FAQ', 'প্রশ্ন-উত্তর', '#faq', false, 40),
  ((select id from public.footer_sections where title_en = 'Platform'), 'mediversebd.com', 'mediversebd.com', 'https://mediversebd.com', true, 10),
  ((select id from public.footer_sections where title_en = 'Platform'), 'Contact', 'যোগাযোগ', '#contact', false, 20),
  ((select id from public.footer_sections where title_en = 'Platform'), 'Privacy Policy', 'প্রাইভেসি পলিসি', 'https://mediversebd.com', true, 30),
  ((select id from public.footer_sections where title_en = 'Platform'), 'Terms of Service', 'শর্তাবলি', 'https://mediversebd.com', true, 40);

insert into public.social_links (platform, url, label_en, label_bn, subtitle_en, subtitle_bn, sort_order) values
  ('facebook', 'https://www.facebook.com/share/18R8eQDysQ/', 'Facebook', 'Facebook', 'Updates & community', 'আপডেট আর কমিউনিটি', 10),
  ('youtube', 'https://youtube.com/@mediversedental?si=VuCm4kPuqcdEORaJ', 'YouTube', 'YouTube', '100+ free classes', '১০০+ ফ্রি ক্লাস', 20),
  ('telegram', 'https://t.me/mvdental', 'Telegram', 'Telegram', 'Notes & notices', 'নোটস আর নোটিশ', 30),
  ('whatsapp', 'https://wa.me/8801726415926?text=Hello%20MediVerse%20Dental%2C%20I%20would%20like%20to%20know%20more%20about%20your%20BDS%20courses.', 'WhatsApp', 'WhatsApp', '+880 1726-415926', '+880 1726-415926', 40);


-- >>>>>>>>>>>>>>>>>>>> self-check >>>>>>>>>>>>>>>>>>>>
-- If anything is missing, stop here and roll everything back.
do $$
declare
  v_courses int := (select count(*) from public.courses);
  v_mentors int := (select count(*) from public.mentors);
  v_media   int := (select count(*) from public.media);
  v_bucket  int := (select count(*) from storage.buckets where id = 'public-media');
  v_no_rls  int := (select count(*) from pg_tables where schemaname = 'public' and not rowsecurity);
begin
  if v_courses <> 22 or v_mentors <> 10 or v_media <> 29 or v_bucket <> 1 or v_no_rls <> 0 then
    raise exception 'Setup self-check failed: courses=%, mentors=%, media=%, bucket=%, tables_without_rls=% — nothing was saved',
      v_courses, v_mentors, v_media, v_bucket, v_no_rls;
  end if;
end;
$$;

commit;

-- Result shown in the SQL Editor (expected: 22 | 10 | 29 | 7 | 1 | 0)
select
  (select count(*) from public.courses)        as courses,
  (select count(*) from public.mentors)        as mentors,
  (select count(*) from public.media)          as images,
  (select count(*) from public.page_sections)  as homepage_sections,
  (select count(*) from storage.buckets where id = 'public-media') as image_bucket,
  (select count(*) from pg_tables where schemaname = 'public' and not rowsecurity) as tables_without_protection;
