"""Combine all migrations + seed into ONE file for the Supabase SQL Editor.

    python3 mediverse-dental/scripts/make_staging_setup.py

Output: supabase/staging_setup.sql — paste it into Supabase → SQL Editor → Run.
It runs as a single transaction: if anything fails, nothing is saved.
It ends with self-checks; if the result is wrong, everything is rolled back.
Regenerate this file whenever a migration or the seed changes.
"""
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
SUPA = ROOT / "supabase"
OUT = SUPA / "staging_setup.sql"

parts = [
    "-- ============================================================================\n"
    "-- MediVerse Dental CMS — ONE-TIME STAGING DATABASE SETUP (generated file)\n"
    "-- Paste this whole file into Supabase → SQL Editor → New query → Run.\n"
    "--   * All-or-nothing: if any line fails, NOTHING is saved.\n"
    "--   * Safe to retry after an error. If it was already applied successfully,\n"
    "--     running it again fails with \"already exists\" and changes nothing.\n"
    "-- Generated by scripts/make_staging_setup.py from supabase/migrations + seed.sql\n"
    "-- ============================================================================\n\n"
    "begin;\n"
]

for f in sorted((SUPA / "migrations").glob("*.sql")):
    parts.append(f"\n-- >>>>>>>>>>>>>>>>>>>> {f.name} >>>>>>>>>>>>>>>>>>>>\n")
    parts.append(f.read_text(encoding="utf-8"))

seed = (SUPA / "seed.sql").read_text(encoding="utf-8")
# The seed has its own begin/commit; the combined file uses one outer transaction.
seed = re.sub(r"^begin;\s*$", "", seed, count=1, flags=re.M)
seed = re.sub(r"^commit;\s*$", "", seed, count=1, flags=re.M)
parts.append("\n-- >>>>>>>>>>>>>>>>>>>> seed.sql >>>>>>>>>>>>>>>>>>>>\n")
parts.append(seed)

parts.append("""
-- >>>>>>>>>>>>>>>>>>>> self-check >>>>>>>>>>>>>>>>>>>>
-- If anything is missing, stop here and roll everything back.
do $$
declare
  v_courses int := (select count(*) from public.courses);
  v_mentors int := (select count(*) from public.mentors);
  v_media   int := (select count(*) from public.media);
  v_bucket  int := (select count(*) from storage.buckets where id = 'public-media');
  v_no_rls  int := (select count(*) from pg_tables where schemaname = 'public' and not rowsecurity);
begin
  if v_courses <> 22 or v_mentors <> 10 or v_media <> 29 or v_bucket <> 1 or v_no_rls <> 0 then
    raise exception 'Setup self-check failed: courses=%, mentors=%, media=%, bucket=%, tables_without_rls=% — nothing was saved',
      v_courses, v_mentors, v_media, v_bucket, v_no_rls;
  end if;
end;
$$;

commit;

-- Result shown in the SQL Editor (expected: 22 | 10 | 29 | 7 | 1 | 0)
select
  (select count(*) from public.courses)        as courses,
  (select count(*) from public.mentors)        as mentors,
  (select count(*) from public.media)          as images,
  (select count(*) from public.page_sections)  as homepage_sections,
  (select count(*) from storage.buckets where id = 'public-media') as image_bucket,
  (select count(*) from pg_tables where schemaname = 'public' and not rowsecurity) as tables_without_protection;
""")

OUT.write_text("".join(parts), encoding="utf-8")
print(f"wrote {OUT.relative_to(ROOT.parent)} ({OUT.stat().st_size // 1024} KB)")
